### ISSUE TITLE
Mailkit OAuth 2.0 integration support

### ISSUE THREAD

**Issue by h2physics** [jstedfast/MailKit#1259] opened 2021-09-20 02:10 UTC
**Describe the bug**
Currently, I am using your MailKit library and integrating with Microsoft OAuth 2.0. Then I am facing trouble when using AccessToken for connecting via IMAP protocol.

I followed with this document https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow (section Request an authorization code and Request an access token with a client_secret). The scopes which I used for both request authorization code and access token are IMAP.AccessAsUser.All, SMTP.Send, offline_access and User.Read (these scopes should be under https://graph.microsoft.com host)

Here is my authorize request
```
https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?
client_id=<client_id>&
redirect_uri=<redirect_uri>&
response_type=code&
scope=https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access profile openid&
access_type=offline&
prompt=consent
```
Then I redeemed access token by this request
```
METHOD POST
https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token

Body: 
{
    "code": "<code>",
    "client_id": "<client_id>",
    "client_secret": "<client_secret>",
    "grant_type": "authorization_code",
    "redirect_uri": "<redirect_uri>",
    "scope": "https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access profile openid"
}

```

I connected and authenticated IMAP via ImapClient's Connect and Authenticate method as the attachment file below. 
```
var imapClient = new ImapClient(new ProtocolLogger("log.txt"));
imapClient.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
try
{
    imapClient.Authenticate(new SaslMechanismOAuth2("<email_address>", "<access_token>"));
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```
Then I got an error A00000001 NO AUTHENTICATE failed (see log.txt file below)

**Platform:**
 - OS: Window
 - .NET Framework: .NET Framework 4.5
 - MailKit Version: 2.15.0

**Exception**
```
MailKit.Security.AuthenticationException: Authentication failed.
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(SaslMechanism mechanism, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Authenticate(SaslMechanism mechanism, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in E:\Self study\source\repos\QandA\backend\ConsoleApp1\ConsoleApp1\Program.cs:line 17
```

**To Reproduce**
1. Go to authorization request link for requesting authentication code
2. Redeem access token using authentication code
3. Connect IMAP Protocol using access token

**Expected behavior**
Connect IMAP successfully

**Screenshots**
I have already granted permission in Azure Portal
![Screenshot from 2021-09-18 17-24-48](https://user-images.githubusercontent.com/18548110/133951232-bd6c546b-656f-41e8-8fdd-2559e09a00e9.png)

**Protocol Logs**
```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [UwBHADIAUABSADAAMQBDAEEAMAAxADMAMQAuAGEAcABjAHAAcgBkADAAMQAuAHAAcgBvAGQALgBlAHgAYwBoAGEAbgBnAGUAbABhAGIAcwAuAGMAbwBtAA==]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 
S: A00000001 NO AUTHENTICATE failed.
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [UwBHADIAUABSADAANgBDAEEAMAAwADkANgAuAGEAcABjAHAAcgBkADAANgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE XOAUTH2 
S: A00000001 NO AUTHENTICATE failed.
```

**Additional context**

**Comment by jstedfast** [comment] 2021-09-20 13:56
Have you tried following these directions? https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md

**Comment by h2physics** [comment] 2021-09-21 00:37
@jstedfast I saw that it's using scope under `https://outlook.office.com`. However in Azure Portal I could only grant scope for `https://graph.microsoft.com`. Do you know how to add scopes for `https://outlook.office.com`?

**Comment by jstedfast** [comment] 2021-09-21 00:59
No, I don't, sorry.

I'm going to close this because it's not an issue with MailKit per-se, it's an issue with obtaining OAuth credentials.

It also seems to be a duplicate of issue #1126

I don't know what the solution is to make this work with Graph and no one else seems to have been able to figure it out.

**Closed by jstedfast** 2021-09-21 00:59 UTC
Labels: question
