### ISSUE TITLE
IMAP and SMTP infrequently hang on connect

### ISSUE THREAD

**Issue by AdamCharron** [jstedfast/MailKit#1186] opened 2021-04-01 18:48 UTC
**Describe the bug**
I was polling the inbox using IMAP (IDLE for 9 minutes, 1 minute delay in between iterations) for ~2 weeks (this failure has taken up to 4-6 weeks to occur in the past). The exception below was encountered while IDLEing. 
**Reconnect after this exception, with a synchronous `ImapClient.Connect("outlook.office365.com", 993, SslOnConnect, cancellationToken (no timeout))` call. This call doesn't return and stays unresponsive infinitely.** 

**Note:** this exception, followed by a **successful reconnect**, had happened multiple times before during this 2 week run. 

This is in version 2.11, after this issue's supposed fix: https://github.com/jstedfast/MailKit/issues/1059

(**Aside:** The same issue with the same signature has also been seen on SMTP with STARTTLS connect after ~300 connects over a one month span. This SMTP issue was seen in 2.7.0, prior to the fix for https://github.com/jstedfast/MailKit/issues/1059, but since it happened on STARTTLS it seems to be unrelated to that fix. )

**Platform (please complete the following information):**
 - OS: Windows Server 2019 & Win10
 - .NET Framework: 4.8
 - MailKit Version: 2.11.0

**Exception**
```
System.IO.IOException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
	at MailKit.Net.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
	--- End of inner exception stack trace ---
	at MailKit.Net.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
	at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
	at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
	at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
	at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
	at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
	at MailKit.Net.Imap.ImapStream.<ReadAheadAsync>d__53.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at MailKit.Net.Imap.ImapStream.<ReadTokenAsync>d__68.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__175.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at MailKit.Net.Imap.ImapEngine.<RunAsync>d__176.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at MailKit.Net.Imap.ImapClient.<IdleAsync>d__102.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at MailKit.Net.Imap.ImapClient.Idle(CancellationToken doneToken, CancellationToken cancellationToken)
	at MyCodeEntryPoint()
```
The application was still alive after this exception and tried to reconnnect.
It had previously successfully reconnected after this exception several times over the 2 week runtime. 

**To Reproduce**
1. Poll the inbox through IMAP IDLE commands for weeks, connecting after each connection-terminating exception.
2. Wait until it stops responding.

**Protocol Logs**
(Some items in <> are muted below for privacy.)
```
<working normally, SEARCH, IDLE, wait cycle repeating with successful reconnects>
2021-03-30 18:35:49.132		C: Y00000531 IDLE
2021-03-30 18:35:49.210		S: + IDLE accepted, awaiting DONE command.
<see exception>
Connected to imaps://outlook.office365.com:993/
2021-03-30 18:39:55.869		S: * OK The Microsoft Exchange IMAP4 service is ready. [<tag>]
2021-03-30 18:39:55.869		C: Z00000000 CAPABILITY
2021-03-30 18:39:55.884		S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
2021-03-30 18:39:55.884		S: Z00000000 OK CAPABILITY completed.
2021-03-30 18:39:55.900		C: Z00000001 AUTHENTICATE PLAIN
2021-03-30 18:39:55.900		S: + 
2021-03-30 18:39:55.900		C: <muted credentials>
2021-03-30 18:39:56.400		S: Z00000001 OK AUTHENTICATE completed.
2021-03-30 18:39:56.400		C: Z00000002 CAPABILITY
2021-03-30 18:39:56.447		S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
2021-03-30 18:39:56.447		S: Z00000002 OK CAPABILITY completed.
2021-03-30 18:39:56.447		C: Z00000003 NAMESPACE
2021-03-30 18:39:56.509		S: * NAMESPACE (("" "/")) NIL NIL
2021-03-30 18:39:56.509		S: Z00000003 OK NAMESPACE completed.
2021-03-30 18:39:56.509		C: Z00000004 LIST "" "INBOX"
2021-03-30 18:39:56.620		S: * LIST (\Marked \HasNoChildren) "/" Inbox
2021-03-30 18:39:56.620		S: Z00000004 OK LIST completed.
2021-03-30 18:39:56.620		C: Z00000005 SELECT Inbox
2021-03-30 18:39:56.683		S: * 0 EXISTS
2021-03-30 18:39:56.683		S: * 0 RECENT
2021-03-30 18:39:56.683		S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
2021-03-30 18:39:56.683		S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
2021-03-30 18:39:56.683		S: * OK [UIDVALIDITY 14] UIDVALIDITY value
2021-03-30 18:39:56.683		S: * OK [UIDNEXT 292] The next unique identifier value
2021-03-30 18:39:56.683		S: Z00000005 OK [READ-WRITE] SELECT completed.
2021-03-30 18:39:56.683		C: Z00000006 LIST "" "%"
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren) "/" Archive
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren \Trash) "/" Deleted
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren \Drafts) "/" Drafts
2021-03-30 18:39:56.745		S: * LIST (\Marked \HasNoChildren) "/" Inbox
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren \Junk) "/" Junk
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren) "/" Notes
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren) "/" Outbox
2021-03-30 18:39:56.745		S: * LIST (\Marked \HasNoChildren) "/" "Folder 1"
2021-03-30 18:39:56.745		S: * LIST (\Marked \HasNoChildren) "/" "Folder 2"
2021-03-30 18:39:56.745		S: * LIST (\HasNoChildren \Sent) "/" Sent
2021-03-30 18:39:56.745		S: Z00000006 OK LIST completed.
2021-03-30 18:39:56.761		C: Z00000007 UID SEARCH ALL
2021-03-30 18:39:56.808		S: * SEARCH
2021-03-30 18:39:56.808		S: Z00000007 OK SEARCH completed.
2021-03-30 18:39:56.808		C: Z00000008 IDLE
2021-03-30 18:39:56.870		S: + IDLE accepted, awaiting DONE command.
2021-03-30 18:48:56.824		C: DONE
2021-03-30 18:48:56.871		S: Z00000008 OK IDLE completed.
<repeat for many hours>
2021-03-31 05:50:06.855		C: Z00000141 UID SEARCH ALL
2021-03-31 05:50:06.902		S: * SEARCH
2021-03-31 05:50:06.902		S: Z00000141 OK SEARCH completed.
2021-03-31 05:50:06.902		C: Z00000142 IDLE
2021-03-31 05:50:06.964		S: + IDLE accepted, awaiting DONE command.
2021-03-31 05:59:06.930		C: DONE
2021-03-31 05:59:06.976		S: Z00000142 OK IDLE completed.
2021-03-31 06:00:07.007		C: Z00000143 UID SEARCH ALL
2021-03-31 06:00:07.054		S: * SEARCH
2021-03-31 06:00:07.054		S: Z00000143 OK SEARCH completed.
2021-03-31 06:00:07.054		C: Z00000144 IDLE
2021-03-31 06:00:07.116		S: + IDLE accepted, awaiting DONE command.
<see exception>
```

**Comment by jstedfast** [comment] 2021-04-06 14:31
According to the exception, the TCP/IP connection was forcibly closed by the remote host. That means there's nothing MailKit can do about it.

**Comment by AdamCharron** [comment] 2021-04-06 14:58
That's not the issue. 
After this exception, when I try to reconnect to either IMAP or SMTP, it hangs in IMAP/SMTP.Connect and never unblocks.
This is even with the timeout fix you added to the [previous MailKit issue I had linked](https://github.com/jstedfast/MailKit/issues/1059). 
This issue here is that (very infrequently) MailKit isn't cancelling or timing out from certain calls and it causes hangs.

**Comment by jstedfast** [comment] 2021-04-06 17:03
Any chance you could attach with a debugger and try to figure out what is going wrong? I'm not sure how to reliably reproduce this and w/o knowing how to repro, I don't think I'll be able to figure out the issue.

**Comment by AdamCharron** [comment] 2021-04-06 18:06
This is where it seems to be getting stuck after calling Connect

![image](https://user-images.githubusercontent.com/11558429/113757809-0d4ead00-96e1-11eb-86d9-9fad6e0dc352.png)

Yeah it's a pain to reproduce, and I haven't found a faster way than just running (IDLE, re-connect on failure) for several weeks.

**Comment by jstedfast** [comment] 2021-04-07 14:58
Looks like it's hanging in the client.AuthenticateAsClientAsync() call (which is what I think you were trying to say now that I reread your initial report) and is exactly the issue that I (thought I) fixed in that other bug report :-\

The good news is that .NET 5 (and .NETStandard 2.1?) has a new AuthenticateAsClientAsync() method that takes a cancellationToken which, I hope, means that it is actually cancellable.

Do you happen to be using either of those?

If not, the best idea that I have right now is to implement my own AuthenticateAsClientAsync() API wrapper on my custom SslStream subclass that would wrap everything in some code that severs the TCP/IP connection on cancel.

**Comment by jstedfast** [comment] 2021-04-07 14:59
Ah, n/m, you are using .NET 4.8 as per initial report.

**Comment by AdamCharron** [comment] 2021-04-07 15:10
Yeah I saw but unfortunately I'm stuck with .NET 4.8 for now.
That would be incredibly helpful though, thanks!

**Comment by jstedfast** [comment] 2021-04-09 18:24
Ohhhhhh.... I somehow missed that the synchronous Connect() method was called.

The fix in issue #1059 was for ConnectAsync, I think.

**Comment by jstedfast** [comment] 2021-04-09 18:26
Never mind, the last fix was to set the timeout before calling SslStream.AuthenticateAsClient/Async() and that issue was for synchronous Connect() as well.

**Comment by jstedfast** [comment] 2021-04-13 12:53
FWIW, based on the stacktrace, it seems that the issue isn't an I/O hang with the SMTP server, but an I/O hang with downloading certificates (over HTTP) from the Certificate Authority (in order to build the cert chain).

**Comment by jstedfast** [comment] 2021-04-13 12:58
I was going to go with something like the following method:

```csharp
public void AuthenticateAsClient (string host, X509CertificateCollection clientCertificates, SslProtocols sslProtocols, bool checkCertificateRevocation, CancellationToken cancellationToken)
{
	cancellationToken.ThrowIfCancellationRequested ();

	using (var timeout = new CancellationTokenSource (ReadTimeout)) {
		using (var linked = CancellationTokenSource.CreateLinkedTokenSource (cancellationToken, timeout.Token)) {
			var network = NetworkStream.Get (InnerStream);

			using (var registration = linked.Token.Register (() => network?.Disconnect (), false)) {
				try {
#if NETSTANDARD1_3 || NETSTANDARD1_6
					AuthenticateAsClientAsync (host, ClientCertificates, SslProtocols, CheckCertificateRevocation).GetAwaiter ().GetResult ();
#else
					AuthenticateAsClient (host, clientCertificates, sslProtocols, checkCertificateRevocation);
#endif
					return;
				} catch {
					cancellationToken.ThrowIfCancellationRequested ();

					if (timeout.IsCancellationRequested)
						throw new TimeoutException ();

					throw;
				}
			}
		}
	}
}
```

But if the problem isn't a hang w/ the SMTP server I/O, then forcing a disconnect with the SMTP server won't cause the SslStream's AuthenticateAsClient() method to abort and so the hang would continue...

Issue #1059 was due to an I/O hang with the IMAP server and so making sure to set the TCP/IP socket I/O timeout *before* calling AuthenticateAsClient meant that we would not get a hang, but this case really is different and I'm not sure how to force the "download intermediate certificates from the CA" logic to abort since there's no way to get access to that.

**Comment by jstedfast** [comment] 2021-04-15 01:20
This is unfixable from the MailKit level. It has to be fixed at the .NET class libraries level.

**Closed by jstedfast** 2021-04-15 01:20 UTC

**Comment by AdamCharron** [comment] 2021-06-25 17:54
Sorry this took so long, it appears to be an AWS issue:
https://blog.wxperts.com/2020/11/20/aws-2019-server-winhttp-web-proxy-auto-discovery-service-errors/ 

Thanks for taking a look though
