### ISSUE TITLE
Add an Example for MimeMessage.CreateFromMailMessage Method

### ISSUE THREAD

**Issue by HektorLolo** [jstedfast/MailKit#1571] opened 2023-05-20 02:22 UTC
Please add an example for MimeMessage.CreateFromMailMessage Method.

In prior versions this line works fine:

var mimeMessage =  MimeKit.MimeMessage.CreateFromMailMessage(Mensaje);

Now with version 4 says that MimeMessage doesnt contain a definition for CreateFromMailMessage error.

How is the new form to do this?

Thanks in advance

Help Topic: http://www.mimekit.net/docs/html/M_MimeKit_MimeMessage_CreateFromMailMessage.htm

**Comment by jstedfast** [comment] 2023-05-20 15:41
This is a duplicate of https://github.com/jstedfast/MimeKit/issues/913

**Closed by jstedfast** 2023-05-20 15:41 UTC
Labels: duplicate
