### ISSUE TITLE
ImapFolder.FetchAsync: ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by komanton** [jstedfast/MailKit#886] opened 2019-07-26 13:40 UTC
From time to time I received this exception. But eventually, it was successfully retrieved after several attempts.
"MailKit" Version="2.1.5.1" 

Stack trace:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at MailKit.Net.Imap.ImapFolder.FetchSummaryContext.OnMessageExpunged(Object sender, MessageEventArgs args)
   at MailKit.Net.Imap.ImapFolder.OnExpunge(Int32 index)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapFolder.GetPreviewTextAsync(FetchSummaryContext sctx, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 uids, MessageSummaryItems items, Boolean doAsync, CancellationToken cancellationToken)
```

```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [TAB*******************************NAA==]     
C: Y00000000 CAPABILITY     
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+     
S: Y00000000 OK CAPABILITY completed.     
C: Y00000001 AUTHENTICATE PLAIN AHN5c************************************Uo=     
S: Y00000001 NO AUTHENTICATE failed.     
C: Y00000002 ****** LOGIN INFORMATION HIDEN ****** completed.     
C: Y00000003 CAPABILITY     
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+     
S: Y00000003 OK CAPABILITY completed.     
C: Y00000004 NAMESPACE     
S: * NAMESPACE (("" "/")) NIL NIL     
S: Y00000004 OK NAMESPACE completed.     
C: Y00000005 LIST "" "INBOX"     
S: * LIST (\Marked \HasNoChildren) "/" INBOX     
S: Y00000005 OK LIST completed.     
C: Y00000006 SELECT INBOX     
S: * 2 EXISTS     
S: * 0 RECENT     
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)     
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags     
S: * OK [UNSEEN 1] Is the first unseen message     
S: * OK [UIDVALIDITY 14] UIDVALIDITY value     
S: * OK [UIDNEXT 689] The next unique identifier value     
S: Y00000006 OK [READ-WRITE] SELECT completed.     
C: Y00000007 UID FETCH 687:687 (UID INTERNALDATE ENVELOPE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (REFERENCES)])     
S: * 1 FETCH (UID 687 INTERNALDATE "19-Jul-2019 06:00:17 +0000" ENVELOPE ("Fri, 19 Jul 2019 06:00:17 +0000" "Undeliverable: Some text - , More text" (("Microsoft Outlook" NIL "MicrosoftExchange329e71ec88ae461b6ce41109e" "somedomain.onmicrosoft.com")) NIL NIL ((NIL NIL "Sometext" "somedomain1.com")) NIL NIL "<3IGHXGCI28U4.BL2U16TY6R483@localhost.localdomain>" "<lksjdlsdkfds.some.domain>") BODYSTRUCTURE ((("text" "plain" ("charset" "us-ascii") NIL NIL "quoted-printable" 7326 155 NIL NIL NIL NIL)("text" "html" ("charset" "us-ascii") NIL NIL "quoted-printable" 7937 161 NIL NIL NIL NIL) "alternative" ("differences" "Content-Type" "boundary" "dc144896-bf7a-449b-8867-297f4e33a7bc") NIL NIL)("message" "delivery-status" NIL NIL NIL "7BIT" 1938 NIL NIL NIL NIL)("message" "rfc822" NIL NIL NIL "7BIT" 0 ("Fri, 19 Jul 2019 06:00:13 +0000" "Rdfgdsf: Some text - , Some more text" (("Some aliace2" NIL "sdfdsf.sdf" "somedomain2.com")) NIL NIL (("sdfdsf@dsfdsfsdf.com" NIL "sdfdsf" "dsafdgdsf.com")) NIL NIL NIL "<3IGHXGCI28U4.BL2U16TY6R483@localhost.localdomain>") ("text" "html" ("charset" "utf-8") "<ZTGHXGCI28U4.C8K2MIOOIDFZ2@localhost.localdomain>" NIL "7BIT" 624 16 NIL NIL NIL NIL) 0 NIL NIL NIL NIL) "report" ("report-type" "delivery-status" "boundary" "ec0f71fc-14dc-4b5a-8d73-946b1c1b9080") NIL "en-US") BODY[HEADER.FIELDS (REFERENCES)] {66}     
S: References: <3IGHXGCI28U4.BL2U16TY6R483@localhost.localdomain>     
S:      
S: )     
S: Y00000007 OK FETCH completed.     
C: Y00000008 UID FETCH 687 (BODY.PEEK[1.1]<0.256>)     
S: * 1 FETCH (BODY[1.1]<0> {256}     
S: Delivery has failed to these recipients or groups:     
S:      
S: firstname.lastname1@somedomain.com<mailto:firstname.lastname1@somedomain.com>     
S: The recipient's mailbox is full and can't accept messages now. Please try r=     
S: esending your message later, or contact the recipient dir UID 687)     
S: * 2 EXPUNGE     
S: * 1 EXISTS     
S: Y00000008 OK FETCH completed.
```

**Comment by jstedfast** [comment] 2019-07-26 15:11
This looks like a duplicate of issue #850 which has already been fixed.

To verify, I plugged your IMAP protocol log into my unit tests and they handle the responses fine and also confirm that the fix I made last time is what made the code execute w/o exception in my unit tests for these responses.

What is happening here is that you are fetching the summary information for a message with an index of `1`. Then you get an `EXPUNGE` notification for the message at index `2` which is beyond the end of the list of message indexes that MailKit knows about based on the FETCH responses it has received so far.

What is then happening in your version of MailKit is that MailKit is then doing `Messages[index]` which throws the `ArgumentOutOfRangeException` in the `OnMessageExpunged` event handler.

Upgrade to 2.2.0 and this issue will go away.

**Closed by jstedfast** 2019-07-26 15:11 UTC
