### ISSUE TITLE
OnNoRecipientsAccepted not being raised when all recipients are non-existent mailboxes

### ISSUE THREAD

**Issue by jhumphries83** [jstedfast/MailKit#491] opened 2017-04-13 17:13 UTC
Hi,

I have overridden the OnNoRecipientsAccepted method of the SmtpClient Class:

```       
protected override void OnNoRecipientsAccepted(MimeMessage message)
{
	if (_recipientExceptions.Count == 1)
		throw _recipientExceptions[0];
		
	throw new AggregateException(_recipientExceptions.ToArray());
}
```

I then send an email to multiple recipients that do not exist.  The OnRecipientNotAccepted is called for each of the non-existent mailboxes but the OnNoRecipientsAccepted is never called.  I would expect OnNoRecipientsAccepted to be called since none of the recipients were accepted.

Instead I receive an error stating "Must have sender and recipient first", which I presume means that the DATA command has been sent despite there being no valid recipients.

Have I misunderstood what OnNoRecipientsAccepted should be used for?

**Comment by jstedfast** [comment] 2017-04-13 17:18
The problem is that you are throwing an exception and so the OnNoRecipientsAccepted code path never gets hit because the thrown exception breaks out of the method before that can get called.

**Comment by jstedfast** [comment] 2017-04-13 17:22
Ah, never mind... I misread your code above. I thought that exception being thrown was in the `OnRecipientNotAccepted()`.

**Comment by jstedfast** [comment] 2017-04-13 17:31
Should be fixed now.

**Closed by jstedfast** 2017-04-13 17:31 UTC
Labels: bug

**Comment by jhumphries83** [comment] 2017-04-19 06:48
That's great thanks! Do you know when you will be making the next release yet?

**Comment by jstedfast** [comment] 2017-04-19 10:11
I might try to make one this weekend. I've been writing a lot more unit tests and uncovering other buglets that no one has run into yet :)

Trying to get every nook and cranny tested by the unit tests, went from 84% to 86% coverage in the past week.
