### ISSUE TITLE
.net core 1.1 ImapClient.connect() throws An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by CodeDoctor34** [jstedfast/MailKit#431] opened 2016-11-23 19:18 UTC
I recently updated my .net core 1.0 app to 1.1 and found that it is no longer working with MailKit. When I attempt client.Connect(MailServer, Port, SSL) it throws "An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll"

**Comment by jstedfast** [comment] 2016-11-23 20:13
Sounds like a duplicate of https://github.com/dotnet/corefx/issues/13814

**Closed by jstedfast** 2016-11-23 20:13 UTC
Labels: duplicate
