### ISSUE TITLE
Xamarin 64bit support is missing

### ISSUE THREAD

**Issue by marcoseraphin** [jstedfast/MailKit#143] opened 2015-01-17 10:55 UTC
Unfortunately I can NOT update my Xamarin project to the unified 64-bit version which is requested by Apple in february.

I am getting the following message:

Adding MailKit...
Attempting to resolve dependency 'MimeKit (≥ 1.0.4.0)'.
Adding 'MailKit 1.0.5.0' to PickMeUp.iOS.
Could not install package 'MailKit 1.0.5.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jstedfast** [comment] 2015-01-18 22:49
this is a duplicate of issue #142

**Closed by jstedfast** 2015-01-18 22:49 UTC
