### ISSUE TITLE
MailKit 2.0.1 is not working on Windows with Mono.

### ISSUE THREAD

**Issue by mikkeljohnsen** [jstedfast/MailKit#631] opened 2018-01-16 09:24 UTC
I have updated to use MailKit instead of SmtpClient in Mono. We are using MailKit 1.20.0 and it works. somwhat, we see corrupt file attachment, so we are trying to update to 2.0.1.

But 2.0.1 is crashing on Windows.

We are using Mono 5.4.1.6 (and 5.8.0.88) on Windows and it worked with 1.20.0.

I don't have any dumps for now.

**Comment by jstedfast** [comment] 2018-01-16 12:27
The main difference between 1.22.0 and 2.0 is that the async support no longer uses Task.Run(), it uses Stream.ReadAsync/WriteAsync throughout the entire stack when you use any of the MimeKit or MailKit Async methods.

If you are getting a corrupt attachment, upgrading to 2.0.1 won't fix that.

Where are you getting a crash? Is it when you do something as trivial as var message = new MimeMessage()? If so, you need an even newer Mono.

**Comment by mikkeljohnsen** [comment] 2018-01-16 12:33
I'm not sure where the crash happen. Windows just come up and say the program has terminated.

What newer Mono do I need ?

**Comment by jstedfast** [comment] 2018-01-16 13:44
I have Mono 5.8.0.103

**Comment by jstedfast** [comment] 2018-01-16 13:46
Generally, if your app crashes and there's no exception, then it's a crash in the runtime (in this case, the Mono runtime) and therefor most likely not a bug in the C#/.NET code that is executing.

**Closed by jstedfast** 2018-01-16 13:46 UTC

**Comment by mikkeljohnsen** [comment] 2018-01-26 09:16
Just updated to Mono 5.8.0.108 on Windows and the MailKit/MimeKit 2.0.1 is still crashing the application.

1.20.0 and 1.22.0 is working fine.

**Comment by mikkeljohnsen** [comment] 2018-01-26 09:20
>	mono-2.0-sgen.dll!mono_local_cprop(MonoCompile * cfg) Line 545	C
 	mono-2.0-sgen.dll!mini_method_compile(_MonoMethod * method, unsigned int opts, _MonoDomain * domain, JitFlags flags, int parts, int aot_method_index) Line 3525	C
 	mono-2.0-sgen.dll!mono_jit_compile_method_inner(_MonoMethod * method, _MonoDomain * target_domain, int opt, _MonoError * error) Line 4167	C
 	mono-2.0-sgen.dll!mono_jit_compile_method_with_opt(_MonoMethod * method, unsigned int opt, int jit_only, _MonoError * error) Line 2130	C
 	mono-2.0-sgen.dll!mono_jit_compile_method(_MonoMethod * method, _MonoError * error) Line 2175	C
 	mono-2.0-sgen.dll!common_call_trampoline(int * regs, unsigned char * code, _MonoMethod * m, MonoVTable * vt, void * * vtable_slot, _MonoError * error) Line 704	C
 	mono-2.0-sgen.dll!mono_vcall_trampoline(int * regs, unsigned char * code, int slot, unsigned char * tramp) Line 915	C
 	[External Code]	
 	[Frames below may be incorrect and/or missing]	
 	mono-2.0-sgen.dll!mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2791	C
 	mono-2.0-sgen.dll!do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2828	C
 	mono-2.0-sgen.dll!mono_runtime_class_init_full(MonoVTable * vtable, _MonoError * error) Line 471	C
 	mono-2.0-sgen.dll!mono_generic_class_init(MonoVTable * vtable) Line 1447	C
 	[External Code]	
 	mono-2.0-sgen.dll!mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2791	C
 	mono-2.0-sgen.dll!do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2828	C
 	mono-2.0-sgen.dll!mono_runtime_class_init_full(MonoVTable * vtable, _MonoError * error) Line 471	C
 	mono-2.0-sgen.dll!mono_method_to_ir(MonoCompile * cfg, _MonoMethod * method, MonoBasicBlock * start_bblock, MonoBasicBlock * end_bblock, MonoInst * return_var, MonoInst * * inline_args, unsigned int inline_offset, int is_virtual_call) Line 10653	C
 	mono-2.0-sgen.dll!mini_method_compile(_MonoMethod * method, unsigned int opts, _MonoDomain * domain, JitFlags flags, int parts, int aot_method_index) Line 3442	C
 	mono-2.0-sgen.dll!mono_jit_compile_method_inner(_MonoMethod * method, _MonoDomain * target_domain, int opt, _MonoError * error) Line 4167	C
 	mono-2.0-sgen.dll!mono_jit_compile_method_with_opt(_MonoMethod * method, unsigned int opt, int jit_only, _MonoError * error) Line 2130	C
 	mono-2.0-sgen.dll!mono_jit_compile_method(_MonoMethod * method, _MonoError * error) Line 2175	C
 	mono-2.0-sgen.dll!common_call_trampoline(int * regs, unsigned char * code, _MonoMethod * m, MonoVTable * vt, void * * vtable_slot, _MonoError * error) Line 704	C
 	mono-2.0-sgen.dll!mono_magic_trampoline(int * regs, unsigned char * code, void * arg, unsigned char * tramp) Line 834	C
 	[External Code]	
 	mono-2.0-sgen.dll!mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2791	C
 	mono-2.0-sgen.dll!do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2828	C
 	mono-2.0-sgen.dll!do_exec_main_checked(_MonoMethod * method, _MonoArray * args, _MonoError * error) Line 4656	C
 	mono-2.0-sgen.dll!mono_runtime_run_main_checked(_MonoMethod * method, int argc, char * * argv, _MonoError * error) Line 4185	C
 	mono-2.0-sgen.dll!mono_jit_exec(_MonoDomain * domain, _MonoAssembly * assembly, int argc, char * * argv) Line 1028	C
 	mono-2.0-sgen.dll!main_thread_handler(void * user_data) Line 1097	C
 	mono-2.0-sgen.dll!mono_main(int argc, char * * argv) Line 2180	C
 	mono.exe!0040122b()	Unknown
 	[External Code]

**Comment by jstedfast** [comment] 2018-01-26 14:14
You should not be getting a crash in the runtime. Can you submit a bug to https://github.com/mono/mono ?
