### ISSUE TITLE
Running on DNX Core on Linux throws exception

### ISSUE THREAD

**Issue by npateman** [jstedfast/MailKit#302] opened 2016-02-10 15:16 UTC
I'm getting this error in Linux on DNX core, works great in full-fat windows.  This also happens in Nano server.

```

10/02/2016 15:12:52 :: EXCEPTION :: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass40_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.Email.EmailQueue.<SendEmailAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MyApp.Email.EmailQueue.MonitorQueue()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Security'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass40_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.Email.EmailQueue.<SendEmailAsync>d__35.MoveNext()<---
```

my code (the send function at least)

```
        private async Task SendEmailAsync(String iHost,
            Int32 iPort,
            Boolean iSSL,
            String iUsername,
            String iPassword,
            String iFromName,
            String iFromEmail,
            String iToName,
            String iToEmail,
            String iSubject,
            String iMessage)
        {
            MimeMessage pMMeMessage = new MimeMessage();
            pMMeMessage.From.Add(new MailboxAddress(iFromName, iFromEmail));
            pMMeMessage.To.Add(new MailboxAddress(iToName, iToEmail));
            pMMeMessage.Subject = iSubject;
            pMMeMessage.Body = new TextPart("plain")
            {
                Text = iMessage
            };
            using (SmtpClient pSCtClient = new SmtpClient())
            {
                await pSCtClient.ConnectAsync(iHost, iPort, iSSL ? MailKit.Security.SecureSocketOptions.StartTls : MailKit.Security.SecureSocketOptions.None);
                pSCtClient.AuthenticationMechanisms.Remove("XOAUTH2");
                await pSCtClient.AuthenticateAsync(iUsername, iPassword);
                await pSCtClient.SendAsync(pMMeMessage);
                await pSCtClient.DisconnectAsync(true);
            }
        }
```

**Comment by npateman** [comment] 2016-02-10 15:24
A related issue I have open on the ASP 5 forums, mixed responses there, neither seem relevant to the issue.
https://forums.asp.net/p/2084419/6019739.aspx?p=True&t=635906856621622126

**Comment by npateman** [comment] 2016-02-10 15:25
What seems to be happening is on full Windows, it's using an assembly in the full framework even though I am only targeting dnxcore. whereas on Nano server and Linux it can't use it so just fails.

**Comment by npateman** [comment] 2016-02-10 15:32
Just tried the latest System.Net.Security nugget package which is (4.0.0-rc2-23623), and I get this,

```
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'Void System.Net.Security.SslStream.AuthenticateAsClient(System.String, System.Security.Cryptography.X509Certificates.X509CertificateCollection, System.Security.Authentication.SslProtocols, Boolean)'.
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
```

the version that works (except for nano server and Linux) is 4.0.0-beta-23516

**Comment by jstedfast** [comment] 2016-02-10 15:48
This is a duplicate of issue #293 

https://github.com/dotnet/corefx/issues/5858 is the issue filed against corefx for this problem.

There appears to be no way for me to fix this on MailKit's side, so closing this until/unless it is discovered that it truly is a problem with MailKit.

**Closed by jstedfast** 2016-02-10 15:48 UTC

**Comment by jstedfast** [comment] 2016-02-10 15:56
FWIW, since MailKit depends on the beta-23516 versions of the various assemblies, it's a bad idea to bump just 1 of them to 23623 because they could move things around and/or the new System.Net.Security might have other dependencies that you have not met, etc.

**Comment by npateman** [comment] 2016-02-10 16:00
Hi there,
I was only "bumping" this one just for a test

**Comment by jstedfast** [comment] 2016-02-10 16:02
I figured that, I just wanted to mention that just in case.

Bugs like this frustrate me because I have no way to fix them, I am completely helpless & dependent on the bugs being solved in corefx :(

(unless, of course, I want to implement my own SslStream which seems like a bad idea)

**Comment by npateman** [comment] 2016-02-10 16:05
Yeah I totally understand, this is the second attempt I've had at getting quite a large project working on all operating systems, and I can't believe everything works except smtp, I thought that would be the easiest bit!

Good luck with your own SslStream, I can imagine that's quite a large job!

**Comment by jstedfast** [comment] 2016-02-10 16:20
I'm sure :)

And yea, it seems that SMTP should be one of the easiest things... But apparently not without a functional SslStream. I suspect that it'll be working by 1.0 final, though.

**Comment by jstedfast** [comment] 2016-02-10 22:08
FWIW, looks like it's been confirmed that the Unix versions of System.Net.Security have not been implemented yet: https://github.com/dotnet/corefx/issues/2483
