### ISSUE TITLE
"Important" folder was introduced instead of the "Inbox" folder in "FolderAttributes" enum

### ISSUE THREAD

**Issue by atiyka** [jstedfast/MailKit#1093] opened 2020-10-30 13:39 UTC
I updated currently the MailKit version from 2.6.0 to 2.9.0 and when I debugged why lots things are messed up in my app, I found that the `FolderAttributes` enum has been changed. The value in the older version for the Inbox folder was 8192, but in the current version is `1 << 14`, which is equal to 16384. This caused my app to use the Important folder as the Inbox folder, because that value was used until now as the value for the Inbox folder.

So as I see, you introduced the Important folder at the place of the Inbox folder, and the rest of the folder values has been shifted (Inbox, Junk, Sent and Trash). I also checked this modification was 5 months ago. 

I had to revert to the older version, because I can't ask all of my users to reinstall their apps because of this issue. What can we do in this situation?

Thanks!

**Comment by jstedfast** [comment] 2020-10-30 15:27
This is a duplicate of https://github.com/jstedfast/MailKit/issues/1063

I'm in the unfortunate position where fixing this will break other people, so I have to mark this wontfix.

That said, as I mentioned in the other bug report, I will need to be more careful in the future to not change the enum values.

When I made that change, I assumed developers would use the enum names rather than values when caching/saving those values. Apparently I was wrong.

The only way I can think of for you to work around this is to add some sort of boolean flag to denote whether you've "upgraded" the cached enum value to the new version or not and then to have a method that converts old values to new values.

Again, I'm sorry for causing this problem.

**Closed by jstedfast** 2020-10-30 15:27 UTC
Labels: bug, duplicate, wontfix

**Comment by atiyka** [comment] 2020-10-30 15:47
Well, this is why every entry sets just one bit, many attributes can be stored in one integer, which is more effective than storing and parsing a string :)

Okay, I'll figure it out how to do.

Thanks for the quick answer
