### ISSUE TITLE
https://Mimekit.net certificate expired and site is extremely slow

### ISSUE THREAD

**Issue by ericnewton76** [jstedfast/MailKit#1679] opened 2023-12-05 18:56 UTC
FYI, https://mimekit.net site is extremely slow to respond to any requests, and the certificate for https://mimekit.net appears to be expired.

I would switch to using github docs so you dont have to host this yourself.

**Comment by jstedfast** [comment] 2023-12-05 19:12
I actually never had an SSL certificate for mimekit.net (when I originally selected a base Azure hosting service plan that I could afford, the one I selected doesn't support SSL).

I haven't heard of GitHub docs - do you mean "GitHub Pages"?

Anyway, that might be a solution to consider. This has been on my TODO list for a while, but I hadn't figured out how to migrate from my current Azure subscription over to a new subscription with SSL certificate support.

**Comment by jstedfast** [comment] 2023-12-29 17:11
Duplicate of https://github.com/jstedfast/MimeKit/issues/707

**Comment by jstedfast** [comment] 2024-01-28 17:03
Working on updating DNS records to point to https://jstedfast.github.io/mimekit.net

Then, once that is updated I'll get an SSL certificate (which it looks like GitHub can do for me if I click a checkbox if I'm understanding the docs correctly)

**Comment by jstedfast** [comment] 2024-02-07 16:11
This should be done in the next day or so. I was finally able to get GitHub Pages to allow me to register mimekit.net (probably could have done this days ago, just needed time for DNS servers to update I guess?)

Anyway, GitHub is generating SSL certificates for mimekit.net and then it should be golden.

**Closed by jstedfast** 2024-02-07 16:11 UTC
Labels: duplicate
