### ISSUE TITLE
await client.AuthenticateAsync (oauth2); ！Authentication failed！

### ISSUE THREAD

**Issue by NeroLiang19** [jstedfast/MailKit#1606] opened 2023-07-13 06:11 UTC
**Describe the bug**

await client.AuthenticateAsync (oauth2);  //Failed!

**Platform (please complete the following information):**
 - OS: [e.g. Windows11.]
 - .NET Runtime: [NET6]
 - .NET Framework: [e.g. .Net Core,.]
 - MailKit Version: 4.1.0

**Exception**
Authentication failed！

var clientId = "xxxxxxxxxb-a0ad-xxxx-b686-xxxxxxxxxx9";
			var tenantId = "xxxxxxxxxx-9414-xxxxxx-a489-xxxxxxxxxde";
			var redirectUri = "http://localhost";
			var clientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSt";
 
			string userName = "xxxxxx@neewer.com";   
 
			var app = ConfidentialClientApplicationBuilder
				.Create(clientId)
				.WithTenantId(tenantId)
				.WithClientSecret(clientSecret)
				.Build();
 
			string[] scopes = { 
				"https://outlook.office365.com/.default"
			};
			
			var result = await app.AcquireTokenForClient(scopes).ExecuteAsync();
			string accessToken = result.AccessToken;

			using (var client = new ImapClient())
			{
				try {
					await client.ConnectAsync ("outlook.office365.com", 993,SecureSocketOptions.SslOnConnect);
					await client.AuthenticateAsync (new SaslMechanismOAuth2 (userName, accessToken));//Failed!!!
					await client.DisconnectAsync (true);
					var inbox = client.Inbox;
				} catch (Exception e) {
					Console.WriteLine (e);
					throw;
				}
			} 

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by NeroLiang19** [comment] 2023-07-13 06:35
![image](https://github.com/jstedfast/MailKit/assets/24262475/fb7ff1c6-f356-4fbe-88a2-7d910a48de4e)

**Comment by jstedfast** [comment] 2023-07-13 11:51
This is a duplicate of issue #1126

**Closed by jstedfast** 2023-07-13 11:51 UTC
Labels: duplicate
