### ISSUE TITLE
Syntax error in BODYSTRUCTURE

### ISSUE THREAD

**Issue by sq5** [jstedfast/MailKit#1840] opened 2024-11-03 07:24 UTC
Hi all

mailkit 4.3, server mail.ru

Error

Syntax error in BODYSTRUCTURE. Unexpected atom token: 1.86931e+06

Stack

 at MailKit.Net.Imap.ImapUtils.ParseBody(ImapEngine engine, String format, String path, CancellationToken cancellationToken)\n   at MailKit.Net.Imap.ImapUtils.ParseMultipart(ImapEngine engine, String format, String path, CancellationToken cancellationToken)\n   at MailKit.Net.Imap.ImapUtils.ParseBody(ImapEngine engine, String format, String path, CancellationToken cancellationToken)\n   at MailKit.Net.Imap.ImapFolder.ParseSummaryItems(ImapEngine engine, MessageSummary message, FetchSummaryItemsCompletedCallback completed, CancellationToken cancellationToken)\n   at MailKit.Net.Imap.ImapFolder.UntaggedFetchSummaryItemsHandler(ImapEngine engine, ImapCommand ic, Int32 index, Boolean doAsync)\n   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)\n   at MailKit.Net.Imap.ImapCommand.Step()\n   at MailKit.Net.Imap.ImapEngine.Iterate()\n   at MailKit.Net.Imap.ImapEngine.Run(ImapCommand ic)\n

Log in attachment
[imap.log](https://github.com/user-attachments/files/17609644/imap.log)

**Comment by jstedfast** [comment] 2024-11-03 13:25
Duplicate of issue #1838

**Closed by jstedfast** 2024-11-03 13:25 UTC
Labels: duplicate
