### ISSUE TITLE
Dotnet 3.0.0 Linux image doesnt seem to use ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by Spaceman1861** [jstedfast/MailKit#951] opened 2019-11-18 00:43 UTC
**Describe the bug**
We have been using this code in production for a while. Post an image upgrade from dotnet 2.1.300 to 3.0.0 it is not hitting the ServerCertificateValidationCallback function any more for IMAP providers with self certificates. When I run on my windows machine or in a windows based image it works fine.

```
public override Task<DefaultResponse> Initialize(MailBox mailBox)
{
    var response = base.Initialize(mailBox);

    MailClient = new ImapClient();
    MailClient.CheckCertificateRevocation = false;
    MailClient.ServerCertificateValidationCallback = MailClientServerCertificateValidationCallback;

    return response;
}

private bool MailClientServerCertificateValidationCallback(
    object sender,
    X509Certificate certificate,
    X509Chain chain,
    SslPolicyErrors sslPolicyErrors
)
{
    if (sslPolicyErrors == SslPolicyErrors.None)
        return true;

    Logger.Warning(
        nameof(Initialize),
        "Invalid Cert",
        sender,
        certificate,
        chain,
        sslPolicyErrors
    );

    // if there are errors in the certificate chain, look at each error to determine the cause.
    if ((sslPolicyErrors & SslPolicyErrors.RemoteCertificateChainErrors) != 0)
    {
        if (chain != null && chain.ChainStatus != null)
        {
            foreach (var status in chain.ChainStatus)
            {
                Logger.Warning(
                    nameof(Initialize),
                    "Chain Status {Status}",
                    status.Status,
                    certificate.Subject,
                    certificate.Issuer
                );

                if (status.Status == X509ChainStatusFlags.RevocationStatusUnknown)
                {
                    Logger.Warning(
                        nameof(Initialize),
                        "Chain Status {status} cant tell if revoked correctly allowing connection",
                        status.Status
                    );

                    continue;
                }

                if (status.Status == X509ChainStatusFlags.PartialChain)
                {
                    Logger.Warning(
                        nameof(Initialize),
                        "PartialChain {status} allowing connection",
                        status.Status
                    );

                    continue;
                }

                if ((certificate.Subject == certificate.Issuer) && (status.Status == X509ChainStatusFlags.UntrustedRoot))
                {
                    Logger.Warning(
                        nameof(Initialize),
                        "PartialChain {status} " +
                        "The only errors in the certificate chain are untrusted root errors for self-signed certificates",
                        status.Status
                    );
                    // self-signed certificates with an untrusted root are valid. 
                    continue;
                }
                else if (status.Status != X509ChainStatusFlags.NoError)
                {
                    // if there are any other errors in the certificate chain, the certificate is invalid,
                    // so the method returns false.
                    return false;
                }
            }
        }
        return true;
    }

    return false;
}
```

It throws this error.

> An unknown error has occurred Exception: An error occurred while attempting to establish an SSL or TLS connection. One possibility is that you are trying to connect to a port which does not support SSL/TLS. The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons: 1. The server is using a self-signed certificate which cannot be verified. 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate. 3. The certificate presented by the server is expired or invalid. See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. Authentication failed because the remote party has closed the transport stream. Data: Source: MailKit Help Link: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate StackTrace: at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken
 at REDACTED.Core.Comms.Services.ServiceBase`1.ConnectAsync(IMailService client, MailServer mailBox, CancellationToken cancellationToken) Source: MailKit BaseException: System.IO.IOException: Authentication failed because the remote party has closed the transport stream. at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest
 at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult
 at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result
 at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult
 at System.Net.Security.SslStream.<>c.b__64_2(IAsyncResult iar
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)

**Expected behavior**
I expect the method to be hit on ssl exception.

**Comment by lukos** [comment] 2019-11-18 11:20
It might be related to #735, which is that the Linux dotnet images are missing a dependency with libcurl, which causes the error but the message is not correct. It would be nice to get a more specific error but I am seeing the same thing: works fine on Windows but not deployed in a Linux Docker container.

**Comment by jstedfast** [comment] 2019-11-18 12:57
When MailKit throws the SslHandshakeException, it includes the original exception thrown by the core framework as the InnerException.

What is the InnerException in this case?

**Comment by Spaceman1861** [comment] 2019-11-18 13:00
I’ll grab it for you when I’m back in the office tomorrow.

**Comment by lukos** [comment] 2019-11-18 14:55
In my case, the inner exception is `System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure`, even though this code runs fine on Windows. I'll see if I can find out anything else.

The cert on the mail relay is from LetsEncrypt if that's relevant. Maybe the Docker image for bionic doesn't have an up-to-date root cert list?

**Comment by lukos** [comment] 2019-11-18 16:04
I'm still stuck. I tried updating the CA list in the docker file but that didn't help. I have shelled into another instance running the same base image (but without the CA updates applied) and I can successfully curl to the letsencrypt site, which is a supposed test for the SSL cert validation. I think maybe this is something more specific to MailKit rather than curl so I will add a new action that sends a mail instantly to see if I can get some more useful log output.

**Comment by jstedfast** [comment] 2019-11-18 22:54
@lukos There's another possibility which is that starting with MailKit 2.3.-something I removed TLS v1.0 from the list of default accepted SslProtocols because it seems that v1.0 has been declared unsafe for over a year.

Of course, it has become apparent that not everyone's mail servers have still not updated their SSL/TLS configurations and still only work with TLS v1.0.

Try doing (before calling Connect):

```csharp
client.SslProtocols |= SslProtocols.Tls;
```

Does that fix it?

**Comment by lukos** [comment] 2019-11-19 08:52
@jstedfast Thanks for the pointer.

In my case, the server is already setup for TLS1.3 using openssl, it tells me that it is using TLS_AES_256_GCM_SHA384. I am going to try another suggestion about logging the results of the server certificate callback to see if that gives any clues. I believe there is a compatability issue with netcore and open ssl 1.1 which should be backported from netcore 3 to 2.2 but might not be working in Ubuntu 18.04.

**Comment by jstedfast** [comment] 2019-11-19 12:05
Okay, keep me updated.

**Comment by lukos** [comment] 2019-11-19 12:18
I'm still none the wiser. I think the only thing it can be is that openssl cannot verify the root cert locally for some reason.

https://github.com/dotnet/corefx/issues/42628

**Comment by lukos** [comment] 2019-11-19 14:51
OK, so the problem is that Lets Encrypt do not include a CRL URL in their certs (to avoid a massively used endpoint being required!) but the default for the SSL connection is to check the CRL status and because this fails, the error is raised.

I don't know if there is a lower level fix that could be applied to check OCSP instead of CRL, apparently, this is possible, but anyway, for now I have simply disabled the CRL checking on the SmtpClient, in our case we are only relaying to trusted servers so I am not too worried about that.

**Comment by lukos** [comment] 2019-11-19 14:52
This is the code which is applied to an `X509Chain`
https://social.msdn.microsoft.com/Forums/en-US/dcf2e392-e80a-4482-941d-7c5c72f570c6/does-x590certificatebuild-use-ocsp-if-chainpolicy-revocationmode-online-is-used?forum=netfxbcl

**Comment by Spaceman1861** [comment] 2019-11-19 23:53
Sorry for the delay @lukos you have been powering ahead i see I wasnt able to get round to getting the logs last night but can you share a code snippet of how you disabled CRL and I will attempt to test it.

**Comment by jstedfast** [comment] 2019-11-20 02:15
@Spaceman1861 I think @lukos is referring to doing:

```csharp
client.CheckCertificateRevocation = false;
```

I should probably add that as a possibility in the docs/FAQ and maybe even the SslHandshakeException message.

**Comment by Spaceman1861** [comment] 2019-11-24 07:31
Sorry for the delay in testing this.

No 1:

`client.CheckCertificateRevocation = false;`

Already had that in the code so nothing to change there.

No 2:

`client.SslProtocols |= SslProtocols.Tls;`

I added this and it didn't change anything.

No 3:

More logging - the inner exception for both clients that are failing for me is

```
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```

So no good news at the moment.

Im going to attempt do something janky with the dotnet core image and install 3.0 ontop of the base image for 2.2 and check that non of the os libs have changed maybe.

**Comment by Spaceman1861** [comment] 2019-11-24 09:05
A further update:

When I roll back to the dotnet 2.1 image then install 3.0 on top of it it works fine without any applications changes.

From:

`#Build Image
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

# Make a working dir
WORKDIR /app
# Copy from local filesystem into working dir
COPY . .
# Publish
RUN dotnet publish SOMEREDACTEDPATH -c Release -o /publish

#Runtime Image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 as final

# Make a working dir
WORKDIR /app

# Copy publish output from last image
COPY --from=build /publish .
# Set Entry Point for Container
ENTRYPOINT ["dotnet", "SOMEREDACTEDPATH"]`

To 

`#Build Image
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

# Make a working dir
WORKDIR /app
# Copy from local filesystem into working dir
COPY . .
# Publish
RUN dotnet publish SOMEREDACTEDPATH -c Release -o /publish

#Runtime Image
FROM microsoft/dotnet:2.1-runtime AS final

# Make a working dir
WORKDIR /app

ENV ASPNETCORE_VERSION 3.0.1
RUN curl -SL --output aspnetcore.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/$ASPNETCORE_VERSION/aspnetcore-runtime-$ASPNETCORE_VERSION-linux-x64.tar.gz \
    && aspnetcore_sha512='f7f6c8e09a9faccb818c42312e77e2fd3d34a7186d611fbe9e77dfb8d02178f31a4f563a5ff8218678cd3c00e7e8e9aef10a69f32f44fdac9a616993c57d1253' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf aspnetcore.tar.gz -C /usr/share/dotnet \
    && rm aspnetcore.tar.gz \
    && ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet

RUN dotnet --info

# Copy publish output from last image
COPY --from=build /publish .
# Set Entry Point for Container
ENTRYPOINT ["dotnet", "SOMEREDACTEDPATH"]`

So my understanding is that from 2.1 to 3.0 the base image has moved from Debian 9 to Debian 10
See - https://hub.docker.com/_/microsoft-dotnet-core-runtime/

2.1.14-stretch-slim, 2.1-stretch-slim, 2.1.14, 2.1 | Dockerfile | Debian 9 | 11/22/2019

3.0.1-buster-slim, 3.0-buster-slim, 3.0.1, 3.0, latest | Dockerfile | Debian 10 | 11/22/2019

So where to from here.

Is this an issue with Debian or DotNet or Mailkit?

Let me know what you think I should do next?

Also thanks for the help so far.

**Comment by jstedfast** [comment] 2019-11-24 14:30
> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
> ...
> Is this an issue with Debian or DotNet or Mailkit?

Normally I would say that that inner exception means there's some sort of network error, but if reinstalling various bits of dotnet fixes this issue, then I guess it seems like a bug in the dotnet runtime or class libraries or something (or perhaps with OpenSSL? I'm not clear on how SslStream uses OpenSSL).

**Comment by shinsetsu** [comment] 2019-12-07 13:47
Drifting through. is this real?

**Comment by Spaceman1861** [comment] 2019-12-08 12:34
@shinsetsu what do you mean by that?

**Comment by Spaceman1861** [comment] 2019-12-11 00:42
Just an update on this due to the workaround working fine this has become a low priority high cost item for us.

We will attempt to diagnose internally.

I don't expect to see an traction any time soon.

I also expect the problem is not the fault of Mailkit.

Let me know if you want me to close this or leave it open for now.

**Comment by jstedfast** [comment] 2019-12-11 15:59
Okay, I'm going to close this for now. If you discover anything else that suggests that it is a bug in MailKit instead, let me know and/or reopen this bug report.

**Closed by jstedfast** 2019-12-11 15:59 UTC
Labels: netcore-bug

**Comment by Spaceman1861** [comment] 2019-12-11 20:50
No worries will do.

Thanks for the help :)

**Comment by pawod** [comment] 2020-02-10 06:40
I just stumbled upon this: 

https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#net-core-30-prefers-openssl-11x-to-openssl-10x

Could this be the cause?

**Comment by Nmaster88** [comment] 2022-10-08 16:38
Dont know if its related but when i try to run a dotnet application that uses mailkit lib in Ubuntu 18 it fails.

Errors:
Exception with message: An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.

**Comment by jstedfast** [comment] 2022-10-08 17:17
@Nmaster88

* which version of MailKit?
* Is it a public mail server?
  * If so, what is the hostname/port?
* Have you tried the following work-around?

```csharp
client.ServerCertificateValidationCallback = (s,c,h,e) => true;
client.Connect (hostName, port, ...);
```

If this work-around works, then it means you don't have the Root CA for your mail server certificate in your local certificate store (on the machine your dotnet client app is running on). You can either import it, or you can write a custom ServerCertificateValidationCallback. The FAQ explains how to do that.

**Comment by Nmaster88** [comment] 2022-10-08 22:14
> * which version of MailKit?
> * Is it a public mail server?
>   
>   * If so, what is the hostname/port?
> * Have you tried the following work-around?
> 
> ```cs
> client.ServerCertificateValidationCallbac
> ```

Hi @jstedfast, thanks for the reply

which version of MailKit?
version 3.3.0

Is it a public mail server?
Yes, its Sapo.pt email, it works well on windows

If so, what is the hostname/port?
Hostname: smtp.sapo.pt
Port: 465

Have you tried the following work-around?
Yes i tried using those 2 lines, although i normally use ConnectAsync.

**Comment by jstedfast** [comment] 2022-10-09 13:14
The FAQ is located here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md

I just tried and I was able to connect to smtp.sapo.pt on port 465 just fine on Windows using MailKit's SmtpClient.

Looks like the bug is in dotnet's SSL implementation if it doesn't work on Linux, or, as I suggested, try importing Root CA certificates (Ubuntu Linux doesn't come with *any* pre-imported into the SSL certificate database).

**Comment by Nmaster88** [comment] 2022-10-09 15:04
> The FAQ is located here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md
> 
> I just tried and I was able to connect to smtp.sapo.pt on port 465 just fine on Windows using MailKit's SmtpClient.
> 
> Looks like the bug is in dotnet's SSL implementation if it doesn't work on Linux, or, as I suggested, try importing Root CA certificates (Ubuntu Linux doesn't come with _any_ pre-imported into the SSL certificate database).

It's always throwing exception when calling this line

`client.ServerCertificateValidationCallback = MySslCertificateValidationCallback`

All of this works on windows but when texting on Linux it fails (i'm developing on windows, so i cannot debug on linux)

I wrote the following callbacks

```
        bool MyServerCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            Console.WriteLine("Before sslPolicyErrors");
            //if (sslPolicyErrors == SslPolicyErrors.None)
            //    return true;

            Console.WriteLine("Before certificate check");
            // Note: The following code casts to an X509Certificate2 because it's easier to get the
            // values for comparison, but it's possible to get them from an X509Certificate as well.
            if (certificate is X509Certificate2 certificate2)
            {
                var cn = certificate2.GetNameInfo(X509NameType.SimpleName, false);
                var fingerprint = certificate2.Thumbprint;
                var serial = certificate2.SerialNumber;
                var issuer = certificate2.Issuer;

                return cn == "*.sapo.pt" && issuer == "CN=Sectigo RSA Organization Validation Secure Server CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB" &&
                    serial == "00A60528CF434881D2C432072BEA8BB85B" &&
                    fingerprint == "7EA9286134890A98D107A5FCEDEE600C41CBE381";
            }

            Console.WriteLine("After certificate check");

            return false;
        }

        bool MySslCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            // If there are no errors, then everything went smoothly.
            if (sslPolicyErrors == SslPolicyErrors.None)
                return true;

            // Note: MailKit will always pass the host name string as the `sender` argument.
            var host = (string)sender;

            if ((sslPolicyErrors & SslPolicyErrors.RemoteCertificateNotAvailable) != 0)
            {
                // This means that the remote certificate is unavailable. Notify the user and return false.
                Console.WriteLine("The SSL certificate was not available for {0}", host);
                return false;
            }

            if ((sslPolicyErrors & SslPolicyErrors.RemoteCertificateNameMismatch) != 0)
            {
                // This means that the server's SSL certificate did not match the host name that we are trying to connect to.
                var certificate2 = certificate as X509Certificate2;
                var cn = certificate2 != null ? certificate2.GetNameInfo(X509NameType.SimpleName, false) : certificate.Subject;

                Console.WriteLine("The Common Name for the SSL certificate did not match {0}. Instead, it was {1}.", host, cn);
                return false;
            }

            // The only other errors left are chain errors.
            Console.WriteLine("The SSL certificate for the server could not be validated for the following reasons:");

            // The first element's certificate will be the server's SSL certificate (and will match the `certificate` argument)
            // while the last element in the chain will typically either be the Root Certificate Authority's certificate -or- it
            // will be a non-authoritative self-signed certificate that the server admin created. 
            foreach (var element in chain.ChainElements)
            {
                // Each element in the chain will have its own status list. If the status list is empty, it means that the
                // certificate itself did not contain any errors.
                if (element.ChainElementStatus.Length == 0)
                    continue;

                Console.WriteLine("\u2022 {0}", element.Certificate.Subject);
                foreach (var error in element.ChainElementStatus)
                {
                    // `error.StatusInformation` contains a human-readable error string while `error.Status` is the corresponding enum value.
                    Console.WriteLine("\t\u2022 {0}", error.StatusInformation);
                }
            }

            return false;
        }

```

Don't know if this makes sense or not, but on Windows it always checks to true on the first if. 
```
            if (sslPolicyErrors == SslPolicyErrors.None)
                return true;
```

Could it be another problem or something i'm missing?

**Comment by jstedfast** [comment] 2022-10-09 16:16
That first if condition always evaluates to true on Windows because Windows has the Root CA certificate in your certificate store.

It evaluates to false on Linux because you *don't* have it installed and so it can't validate the certificate.
