### ISSUE TITLE
Cannot install, dependency loop detected

### ISSUE THREAD

**Issue by Liturgist** [jstedfast/MailKit#1774] opened 2024-07-15 17:28 UTC
**Describe the bug**
```
PS C:\> Install-Package -Name MailKit

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nugetRepository'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package: Dependency loop detected for package 'MailKit'.
```

**Platform (please complete the following information):**
```
Caption             : Microsoft Windows 10 Pro
Version             : 10.0.19045
PSVersion           : 7.4.3
DisplayVersion      : 22H2
BuildType           : Multiprocessor Free
OSArchitecture      : 64-bit
TotalPhysicalMemory : 31.86 GiB
```

```
PS C:\> dotnet --info
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.ee591633
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    8.0.40/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.40\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    34.0.95/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.302 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Expected behavior**
MailKit package is installed.

**Comment by elachlan** [comment] 2024-07-15 23:35
maybe related #1772

**Comment by Liturgist** [comment] 2024-07-16 12:35
Not better in 4.7.1.1.

```
PS C:\Users\pwatson> Find-Package -Name MailKit

Name                           Version          Source           Summary
----                           -------          ------           -------
MailKit                        4.7.1.1          nugetRepository  An Open Source .NET mail-client library for Windows, Mac, Linux, and mobile platforms such as iOS an…

PS C:\Users\pwatson> Install-Package -Name MailKit

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nugetRepository'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package: Dependency loop detected for package 'MailKit'.
```

**Comment by jstedfast** [comment] 2024-07-16 14:49
I'm not sure what the problem could be :(

**Comment by jstedfast** [comment] 2024-07-16 14:56
Probably a duplicate of this: https://github.com/jstedfast/MimeKit/issues/826

That user named their project MailKit.

**Closed by jstedfast** 2024-07-16 14:56 UTC
