### ISSUE TITLE
Exceptions in Disposition during folder listing

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MailKit#486] opened 2017-04-06 09:29 UTC
Hi,

The following exception occurs when listing a folder:

```
Exception: Illegal characters in disposition value.
Parameter name: value
```

The IMAP protocol logging:

```
C: B00000020 FETCH 1:* (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE)
S: * 1 FETCH (UID 3 FLAGS (\Seen) INTERNALDATE " 6-Apr-2017 10:50:20 +0200" RFC822.SIZE 1315 ENVELOPE ("Thu, 6 Apr 2017 10:50:20 +0200" "test" ((NIL NIL "test" "acme.com")) ((NIL NIL "test" "acme.com")) ((NIL NIL "test" "acme.com")) NIL NIL NIL NIL "<58B634343442A1@acme.com>") BODYSTRUCTURE (((("TEXT" "PLAIN" NIL NIL NIL "7bit" 3 1) "ALTERNATIVE" ("boundary" "==boundary-2"))("IMAGE" "GIF" ("name" "image1.gif") "<PHP-image-1>" NIL "base64" 6 NIL ({8}
S: "inline" NIL)) "RELATED" ("boundary" "==boundary-3")) "MIXED" ("boundary" "==boundary-1")))
```

The original mail contains the following MIME part headers:

```
--==boundary-3
Content-type: image/gif; name="image1.gif"
Content-Transfer-Encoding: base64
Content-ID: <PHP-image-1>
Content-Disposition: "inline"
```

Another exception occurring is:

```
Exception: The disposition is not allowed to be empty.
Parameter name: value
```

The IMAP protocol logging:

```
C: M00000020 FETCH 1:* (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE)
S: * 1 FETCH (UID 5 FLAGS (\Seen) INTERNALDATE " 6-Apr-2017 10:59:05 +0200" RFC822.SIZE 1300 ENVELOPE ("Thu, 6 Apr 2017 10:59:05 +0200" "test" ((NIL NIL "test" "acme.com")) ((NIL NIL "test" "acme.com")) ((NIL NIL "test" "acme.com")) NIL NIL NIL NIL "<58B634343442A2@acme.com>") BODYSTRUCTURE (((("TEXT" "PLAIN" NIL NIL NIL "7bit" 0 0) "ALTERNATIVE" ("boundary" "==boundary-2"))("APPLICATION" "PDF" ("name" "file.pdf") NIL NIL "base64" 6 NIL ("" ("filename" "file.pdf"))) "RELATED" ("boundary" "==boundary-3")) "MIXED" ("boundary" "==boundary-1")))
```

The original mail contains the following MIME part headers:

```
--==boundary-3
Content-Type: application/pdf; name="file.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: ; filename="file.pdf"
```

Is there are a solution possible for these invalid disposition headers within MailKit/MimeKit?

Thanks!

**Comment by jstedfast** [comment] 2017-04-06 10:34
As far as I can tell, this can't happen unless you ToString() the MessageSummary and then parse it back? From what I can tell, these exceptions must be coming from BodyPart.TryParse()?

**Comment by jstedfast** [comment] 2017-04-06 11:09
Added 2 work-arounds for these in the ContentDisposition parser in MimeKit, but that's not where you were getting these exceptions from...

**Comment by breedbekkikker** [comment] 2017-04-06 11:23
Here's where the exception occurs:

```
public async Task<IEnumerable<IMessageSummary>> GetMessageSummaryForAllMessagesAsync(IMailFolder mailFolder)
{
   try
   {
      await mailFolder.OpenAsync(FolderAccess.ReadOnly);
      IEnumerable<IMessageSummary> messageSummaries = await mailFolder.FetchAsync(0, -1, SummaryItems);

      return messageSummaries;
   }
   catch (Exception exception)
   {
      throw new Exception("Retrieving MessageSummaries failed", exception);
   }
}
```

MessageSummaries:

```
private const MessageSummaryItems SummaryItems = MessageSummaryItems.BodyStructure |
                                                       MessageSummaryItems.InternalDate |
                                                       MessageSummaryItems.Envelope |
                                                       MessageSummaryItems.Flags |
                                                       MessageSummaryItems.MessageSize |
                                                       MessageSummaryItems.UniqueId;

```

**Comment by jstedfast** [comment] 2017-04-06 12:19
Can you provide a stack trace? I get that it's happening there, but I need more specifics because I don't see how it's possible to hit those particular exceptions.

The problem is, the only way to hit both of those exceptions are:

```csharp
new ContentDisposition ("\"inline\"");
```

or

```csharp
disposition.Disposition = "\"inline\"";
```

The problem is that *neither* of those occur anywhere in ImapUtils.cs where the ContentDisposition is "parsed" from the IMAP FETCH response.

Instead, what that code does is construct a string from the response and then calls ContentDisposition.TryParse() which sets the `disposition` member variable directly instead of via the `Disposition` property which is where the validation occurs.

The only place I can find in both MimeKit and MailKit that *could* emit these exceptions is in the `BodyPart.TryParse()` method which is never used within MailKit, but is there for consumers to use if they serialize the `IMessageSummary.Body` and then parse it back.

**Comment by jstedfast** [comment] 2017-04-06 12:23
Wait, never mind... I found where ImapUtils.cs calls `new ContentDisposition (str)`

**Comment by jstedfast** [comment] 2017-04-06 12:25
ok, fixed now :)

**Closed** 2017-04-06 12:24 UTC

**Comment by jstedfast** [comment] 2017-04-06 12:26
On the plus side, I also added similar work-arounds to MimeKit's parser... (not that it would throw exceptions before, but the `MimePart.ContentDisposition` would be null before due to being unable to parse those cases).

**Comment by breedbekkikker** [comment] 2017-04-06 12:28
Perfect! Thanks a lot!

**Comment by jstedfast** [comment] 2017-04-09 16:55
MimeKit & MailKit 1.14 have been released with this fix.
