### ISSUE TITLE
ImapClient.IdleAsync() is broken for MailKit >= 2.1.4

### ISSUE THREAD

**Issue by nelsonroliveira** [jstedfast/MailKit#942] opened 2019-10-28 19:29 UTC
## Issue
`System.ObjectDisposedException` is thrown if the `done` token is canceled while `IdleAsync` is running.

App was crashing every 9 minutes, changing IdleClient.cs#L100 to a shorter time revealed the problem.

https://github.com/jstedfast/MailKit/blob/44409591e0b96e6e4453a63b3e17dd557acece23/samples/ImapIdle/ImapIdle/IdleClient.cs#L100-L107

## System

The sample code was converted to .net core 3.0.100
Issue was found in Mailkit versions released after 2.1.3
Imap server is outlook.office365.com

## StackTrace:

```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [CENSORED]
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN CENSORED
S: A00000001 OK AUTHENTICATE completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK NAMESPACE completed.
C: A00000004 LIST "" "INBOX"
S: * LIST (\Marked \HasNoChildren) "/" INBOX
S: A00000004 OK LIST completed.
C: A00000005 SELECT INBOX
S: * 15 EXISTS
S: * 0 RECENT
S: * FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
S: * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
S: * OK [UIDVALIDITY 14] UIDVALIDITY value
S: * OK [UIDNEXT 49] The next unique identifier value
S: A00000005 OK [READ-WRITE] SELECT completed.
C: A00000006 UID SEARCH UNSEEN
S: * SEARCH
S: A00000006 OK SEARCH completed.
C: A00000007 IDLE
S: + IDLE accepted, awaiting DONE command.
System.ObjectDisposedException - Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_ReceiveTimeout(Int32 value)
   at MailKit.Net.NetworkStream.set_ReadTimeout(Int32 value)
   at System.Net.Security.SslStream.set_ReadTimeout(Int32 value)
   at MailKit.Net.Imap.ImapStream.set_ReadTimeout(Int32 value)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapClient.IdleAsync(CancellationToken doneToken, Boolean doAsync, CancellationToken cancellationToken)
   at Demo.IdleClient.WaitForNewMessagesAsync() in C:\path\IdleClient.cs:line 245
   at Demo.IdleClient.IdleAsync() in C:\path\IdleClient.cs:line 282
   at Demo.IdleClient.RunAsync() in C:\path\IdleClient.cs:line 326
```

**Comment by jstedfast** [comment] 2019-10-28 19:35
What lead up to this? Do you have the IMAP protocol logs?

Also: try upgrading. 2.1.3 is ~8+ months old.

**Comment by nelsonroliveira** [comment] 2019-10-29 13:51
Fixed a tipo on the `done` variable and included the IMAP logs.

Just to clarify, the issue happens in versions released **after** 2.1.3, the included trace and logs where done on 2.3.2

**Comment by jstedfast** [comment] 2019-10-29 17:59
Thanks, yea, I originally didn't see that you had stated that that this issue affects releases *after* 2.1.3.

**Comment by jstedfast** [comment] 2019-10-30 03:02
This should be fixed now. If you can, I would appreciate if you could verify. Thanks!

**Comment by jstedfast** [comment] 2019-10-30 17:55
Hmmm, the old code worked for .NET 4.5 as well...

I bet .NET Core's SslStream is in a broken state now... :-\

I don't really want to write my own SslStream. *sigh*

**Comment by jstedfast** [comment] 2019-10-31 23:37
What OS are you running this on? I think the dotnet core runtime might use an SslStream that depends on native libs on some platforms?

**Comment by jstedfast** [comment] 2019-11-01 02:46
*Sigh*. Just as I was committing this, I realized the SslStream.ReadAsync() solution could potentially lead to other problems if the `SslStream` already has the remainder of the response buffered from a previous call :-\

Oh well, back to the drawing board...

**Comment by nelsonroliveira** [comment] 2019-11-01 06:06
System was windows 10, I can test it on docker/linux tomorrow

**Comment by jstedfast** [comment] 2019-11-01 12:38
If it's not working on Windows, it probably doesn't work on Linux.

That said, I have some ideas...

**Comment by jstedfast** [comment] 2019-11-01 13:27
This commit *may* fix the issue: https://github.com/jstedfast/MailKit/commit/fc849dbe8f362a7047761b9cf9c5a576b3091016

**Comment by jstedfast** [comment] 2019-11-01 13:50
Ok, that commit works with .NET 4.5 and .NETCore 3.1 on Mac.

If you could verify the fix on Windows 10 and Linux for me, that would be awesome.

Thanks!

**Comment by nelsonroliveira** [comment] 2019-11-01 20:02
Tested ok on:

* Windows 10
* Docker images based on mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim
* Ubuntu Server 18.04.3

**Comment by jstedfast** [comment] 2019-11-01 20:32
Excellent! Thanks! I'll try to make a release this weekend.

**Closed by jstedfast** 2019-11-01 20:32 UTC
Labels: bug

**Comment by jstedfast** [comment] 2019-11-02 18:32
Ok, so I had second thoughts about my fix... it just didn't feel very "clean" by depending on Task.Delay() in order to poll the socket asynchronously for new data.

This new solution goes back to using async I/O by simplifying the logic a bit. Previous logic required that both the `doneToken` *and* the `cancellationToken` would interrupt waiting for data on the socket, probably because *originally* (as in back in 2014 - see issue #61) the logic to send the `"DONE\r\n"` command was located inside of `ImapCommand.StepAsync()` when an `OperationCanceledException` was caught and the exception was caused by the `doneToken` being cancelled. Later, in commit edd0cc57a67c4d4fba95b20130a6f80bfd1dd85f, I moved the logic to send the `"DONE\r\n`" command out of that loop as part of a CancellationToken callback method, but for whatever reason, I kept the requirement that cancelling the `doneToken` would still interrupt the call to `ReadToken()`.

Anyway... I don't think that was needed and testing this new code on .NET 4.5 and .NETCore seems to work fine, at least on Mac.

I'm going to hold off on making a release until you can confirm it still works on Windows/Linux (altho I might go down into my basement to boot up my Windows box to test on that).

**Comment by nelsonroliveira** [comment] 2019-11-02 20:19
Re-tested ok on:

* Windows 10
* Docker images based on mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim
* Ubuntu Server 18.04.3

Interesting use of a token callback.

**Comment by jstedfast** [comment] 2019-11-02 23:37
Awesome, thanks for verifying! I’ll make that release tomorrow.

**Comment by jstedfast** [comment] 2019-11-02 23:38
FWIW, I also verified that this fix works using the synchronous API as well.
