### ISSUE TITLE
IMAP gets stuck when authenticating

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#209] opened 2015-06-25 13:08 UTC
Hi,

I don't know why but for some reason the ImapClient gets stuck when trying to authenticatie to an Exhcnage 2013 server with plain authentication.

I have a mailbox that is connected to an Microsoft active directory account. Don't know if that is giving a problem but for some reason the Authenticate method just fails.

I tried to do the same with ImapX and this client works without any problems.

                //using (var memoryStream = new MemoryStream())
                //using (var protocolLogger = new ProtocolLogger(memoryStream))
                //using (var client = new ImapClient(protocolLogger))
                //{
                //    try
                //    {
                //        client.Timeout = 1000;
                //        MessageBox.Show("Test1");
                //        client.ServerCertificateValidationCallback += ServerCertificateValidationCallback;
                //        MessageBox.Show("Test2");
                //        client.Connect("mail.a3cd.local", 993, true);
                //        MessageBox.Show("Test3");
                //        client.Authenticate("eurtld/aa_gits_demonstratie", ".......");
                //        client.Inbox.Open(FolderAccess.ReadOnly);
                //        var count = client.Inbox.Count;
                //        var result = string.Format(CultureInfo.CurrentCulture,
                //            "Mailbox '{0}' kan geopend worden en bevat '{1}' {2}", Name, count,
                //            ((count == 1) ? "E-mail" : "E-mails"));

                //        client.Disconnect(true);
                //        WriteLoginInformation(memoryStream);
                //        MessageBox.Show(result);
                //    }
                //    catch (Exception exception)
                //    {
                //        WriteLoginInformation(memoryStream);
                //        MessageBox.Show(exception.Message);
                //    }
            //    }
                var client = new ImapX.ImapClient();
                client.Connect("mail.a3cd.local", 993, true, false);
                client.Login("eurtld/aa_gits_demonstratie", ".......");
                MessageBox.Show("succes");

Any ideas why MailKit doesnt work on a Windows 2012R2 server?
My project is set to .NET 4.0

Greetings,
Kees van Spelde

**Comment by jstedfast** [comment] 2015-06-25 13:13
Can you get me a protocol log? These are impossible to debug without a log.

**Comment by Sicos1977** [comment] 2015-06-25 13:24
It just looks like there is some kind of deadlock occurring inside the MimeKit dll.

When I leave away this line: client.ServerCertificateValidationCallback += ServerCertificateValidationCallback;

Then I get to the Authentication part... and then that one fails.

When I enable the certificate line then the code fails on the  client.Connect("mail.a3cd.local", 993, true); line. It looks like the IMAP server closes the connection. After that the ServerCertificateValidationCallback gets fired... and the code fails.

Connected to imaps://mail.a3cd.local:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * BYE Connection is closed. 13

**Comment by jstedfast** [comment] 2015-06-25 13:26
Why are you using +=  instead of just =?

**Comment by Sicos1977** [comment] 2015-06-25 13:27
That was just a typo... already fixed it

**Comment by Sicos1977** [comment] 2015-06-25 13:29
I still think there is some kind of threading deadlock occurring... are you using threads inside MailKit to process for example the IMAP commands?

**Comment by jstedfast** [comment] 2015-06-25 13:29
I'm not using any threads, so any deadlock you have has to be in your own code.

**Comment by Sicos1977** [comment] 2015-06-25 13:30
That should be impossible.. I just made a new form application with nothing else inside it.. and that one also fails

**Comment by jstedfast** [comment] 2015-06-25 13:31
The difference between what you are doing with ImapX and MailKit is that for ImapX, you are not setting a ServerCertificateCallback method - and you said that's where the deadlock is, right?

**Comment by Sicos1977** [comment] 2015-06-25 13:31
I'll try to compile it for .net 4.5 and see what that one does do

**Comment by Sicos1977** [comment] 2015-06-25 13:32
No ... the deadlock occurs over there when I add that line.
When I just leave away this line then the code fails when the Authenticate method is called

**Comment by jstedfast** [comment] 2015-06-25 13:33
Can you get me a protocol log of it failing with Authenticate? You can X-out the actual uer/pass, but I need the rest of the dialog.

**Comment by Sicos1977** [comment] 2015-06-25 13:33
Connected to imaps://mail.a3cd.local:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN

**Comment by jstedfast** [comment] 2015-06-25 13:34
Does it hang there? If so, it's because it is waiting for the Exchange server to send a `+` response.

**Comment by Sicos1977** [comment] 2015-06-25 13:35
Yeah but why does ImapX work without any problems?
I could not see anything difference ... the login is also with PLAIN and that works just fine

**Comment by jstedfast** [comment] 2015-06-25 13:36
Does it not wait for the server to send a `+` response?

**Comment by Sicos1977** [comment] 2015-06-25 13:37
Don't know.... didn't see if there is some kind of protocol logger inside the code... just tried it because I was getting a little bit frustrated... 

I'm now making a test program with .NET 4.5... see if that makes any differences

**Comment by jstedfast** [comment] 2015-06-25 13:40
.NET 4.5 won't make a difference.

Try this:

```csharp
client.AuthenticationMechanisms.Clear ();
client.Authenticate ("username", "password");
```

**Comment by Sicos1977** [comment] 2015-06-25 13:42
Doesn't make a difference

**Comment by jstedfast** [comment] 2015-06-25 13:43
It should. It will send completely different login commands.

**Comment by Sicos1977** [comment] 2015-06-25 13:47
Connected to imaps://mail.a3cd.local:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * BYE Connection is closed. 13

**Comment by jstedfast** [comment] 2015-06-25 13:49
That log means that the IMAP server is immediately closing the connection after it connects - there's nothing I can do about that.

**Comment by Sicos1977** [comment] 2015-06-25 13:50
But why does ImapX work? Don't think that one is so special?

**Comment by Sicos1977** [comment] 2015-06-25 13:52
Thats without the certifcate callback

Connected to imaps://mail.a3cd.local:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 AUTHENTICATE PLAIN

**Comment by jstedfast** [comment] 2015-06-25 13:54
You aren't clearing the AuthenticationMechanisms. Try clearing that.

And if the ServerCertificateCallback is making it exit immediately after connecting, why not stop using it?

**Comment by jstedfast** [comment] 2015-06-25 13:56
ImapX isn't sending `AUTHENTICATE PLAIN`, it is sending `LOGIN "user" "pass"`which i why I keep telling you to clear the AuthenticationMechanisms property right before calling `Authenitcate()`.

**Comment by Sicos1977** [comment] 2015-06-25 13:59
I did clear it.

                        client.Connect("mail.a3cd.local", 993, true);
                        client.AuthenticationMechanisms.Clear();
                        client.Authenticate("eurtld/aa_gits_demonstratie", ".....");
                        client.Inbox.Open(FolderAccess.ReadOnly);
                        var count = client.Inbox.Count;
                        var result = string.Format(CultureInfo.CurrentCulture,
                            "Mailbox '{0}' kan geopend worden en bevat '{1}' {2}", Name, count,
                            ((count == 1) ? "E-mail" : "E-mails"));

                        WriteLoginInformation(memoryStream);
                        client.Disconnect(true);
                        MessageBox.Show(result);

**Comment by Sicos1977** [comment] 2015-06-25 14:00
Connected to imaps://mail.a3cd.local:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 LOGIN eurtld/aa_gits_demonstratie ......

**Comment by jstedfast** [comment] 2015-06-25 14:00
And it hangs after it sends LOGIN ...?

**Comment by Sicos1977** [comment] 2015-06-25 14:01
Yes

**Comment by jstedfast** [comment] 2015-06-25 14:01
Does the server reply?

**Comment by Sicos1977** [comment] 2015-06-25 14:02
Nope....

Thats all the logging I get from the protocollogger... don't know if it did send back a +

**Comment by jstedfast** [comment] 2015-06-25 14:03
It doesn't need to send a + with LOGIN, that LOGIN command is the full command.

All it needs to get back is an `OK`.

Looks like you've got another bug in your IMAP server. This is not a bug in MailKit.

If the server does not reply, then this can't possibly be a bug in MailKit.

You can confirm this with wireshark or some other network packet sniffer, but I guarantee if there's nothing showing up in the log, then the server is not responding.

**Closed by jstedfast** 2015-06-25 14:03 UTC

**Comment by jstedfast** [comment] 2015-06-25 14:23
Actually, I just realized you probably won't be able to confirm with Wireshark because you are using SSL which makes reading the TCP traffic impossible.

I'm telling you, though, that there is no bug in MailKit. MailKit follows the IMAP protocol specifications correctly. This works flawlessly on every other IMAP server except yours, even other Exchange IMAP servers, so I have no idea why it doesn't work for you.

If you step through the code in a debugger, I would bet anything that the "hang" is in ImapStream.ReadAhead() in a Stream.Read() call because it is trying to read a response from the server that the server is simply not sending.

I notice you change the Timeout value. I guarantee that's the wrong thing to do and may have even been causing your disconnect immediately after connecting (that `* BYE` response you were getting).

You didn't do that for ImapX. Nor did you set a ServerCertificateValidationCallback.

**Comment by Sicos1977** [comment] 2015-06-25 16:04
I tried all kind of possibilities to find out why the code isn't working. Also the timeout and certificate callback. The original code I wrote didn't have these lines, I got a little bit frustrated so I was experimenting with settings to see if that would make any difference.

I also have the problems when I use a normal connection without SSL. So I'll give it a new try tomorrow without SSL and see what WireShark turns up. 

To bad that I can't get any logging from the IMAP server. It is an Exchange 2013 server that is hosted at an external provider. Actually it is a shared mail environment that is used in our company. The servers are maintained by a company called ATOS. But that party want to do things the cheap way so the maintenance and technical things are done by another department in another country... what makes it even easier for me to find out was is going wrong ... NOT.

I like your library.. it always worked correct an another mail environment... but that was an Exchange 2007 environment with NTLM authentication.

Somewhere and somehow something is changed and it's my work to find our what... :-)

Thanks for all the help anyway.

**Comment by Sicos1977** [comment] 2015-06-26 12:07
Hi,

I got it working when I use this connection line:
client.Connect("mail.a3cd.local", 143, SecureSocketOptions.None);

But when I try it like this:
client.Connect("mail.a3cd.local", 993, SecureSocketOptions.SslOnConnect);
or this:
client.Connect("mail.a3cd.local", 993, true);

Then it fails again.. do you have any wild guess where to look for this behavior?

**Comment by jstedfast** [comment] 2015-06-26 13:12
`client.Connect("mail.a3cd.local", 993, true);` just calls `client.Connect("mail.a3cd.local", 993, SecureSocketOptions.SslOnConnect);` - it's just a convenience API (just an FYI).

If it hangs with SslStream but not NetworkStream (which is the only difference), then the problem has something to do with the SslStream waiting for more data from the server.

I'm not sure how to debug that, unfortunately.

**Comment by Sicos1977** [comment] 2015-06-26 13:42
I don't know if it makes any difference (I'm no IMAP expert)... but ImapX works with SSL. I compared your code against ImapX code... and the only difference I see when logging in is that they put double quotes around the login name and password and that they encode the string with UTF8.

 public const string Login = "LOGIN \"{0}\" \"{1}\"";
string.Format(ImapCommands.Authenticate + "\n{1}\n{2}", "PLAIN", Base64.ToBase64(Encoding.UTF8.GetBytes(Login)), Base64.ToBase64(Encoding.UTF8.GetBytes(Password))) : string.Format(ImapCommands.Login, Login, Password);

**Comment by jstedfast** [comment] 2015-06-26 14:17
You only need to use quotes if the user name or password contains a space

**Comment by jstedfast** [comment] 2015-06-26 14:40
Oh, btw, MailKit also encodes as UTF8.

ImapX will totally break if the user name or password contains a double quote :-)

Anyway, you can test the theory about double quotes (who knows, maybe Exchange is broken and expects double quotes even when the protocol specification says they aren't needed) by changing this line in ImapClient.cs:

```csharp
ic = engine.QueueCommand (cancellationToken, null, "LOGIN %S %S\r\n", cred.UserName, cred.Password);
```

to

```csharp
ic = engine.QueueCommand (cancellationToken, null, "LOGIN \"%s\" \"%s\"\r\n", cred.UserName, cred.Password);
```

**Comment by eionsimonelli** [comment] 2019-07-19 12:31
@jstedfast @Sicos1977 Did you guys ever sort out this issue? You must not implement the protocol perfectly. We are currently seeing the same issue.

**Comment by jstedfast** [comment] 2019-07-19 12:43
@eionsimonelli try getting me a protocol log so I can see what is going on with your setup.

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log"))
```

Make sure to X-out the base64 blobs in the AUTHENTICATE command(s) when posting the log to a GitHub comment, but keep the original log in case we need to refer back to it.

**Comment by jstedfast** [comment] 2019-07-19 12:59
Let me also ask this:

Does your password (or username, I suppose) contain any of the following characters?

`(`, `)`, `{`,  `<SPACE>`, `<TAB>`, `%`, `*`, `\`, `"`, `]`, or any `CTRL` characters

What aout `}` or `[` ?

How about unicode characters?

**Comment by jstedfast** [comment] 2019-07-19 13:41
@eionsimonelli why did you delete your comment? Are things working for you now? If not, I would love to try and help you figure this out so we can get it resolved.
