### ISSUE TITLE
Attachment not working from Windows 7 and 8

### ISSUE THREAD

**Issue by mikkeljohnsen** [jstedfast/MailKit#633] opened 2018-01-16 14:17 UTC
When attaching a file (other than a text file), like a PDF or Image the file is corrupt when using Windows 7 and 8.

It works fine from Windows 10.

We are use
`
var builder = new BodyBuilder();
builder.Attachments.Add(filepath);
`

We are also experiencing with other method, lilke inline attachement and MimePart. But nothing works on Windows 7 and 8.

We are using Mono 5.4.1.6. And is the same when running on Windows 10.

**Comment by mikkeljohnsen** [comment] 2018-01-16 14:19
We see invalid base64 chars in the message when generated on Windows 7 but not on Windows 10.

**Comment by jstedfast** [comment] 2018-01-16 14:50
Is there any way for you to step through the debugger to figure out how that byte is getting there?

THere's no chance of me being able to debug this as I do not have a Windows 7 machine - all I have is Windows 10, Mac and Linux (all of which do not have this problem).

I suspect that it's not a bug in MimeKit at all (based on the fact that it is specific to Windows 7), but rather a bug in the runtime, but I have no way of knowing for sure.

a simple test case would be:

```csharp
using System;
using System.IO;

using MimeKit.Encodings;

namespace Base64Test {
    class Program
    {
        public static void Main ()
        {
            var encoder = new Base64Encoder ();

            using (var stream = File.OpenRead ("path\\to\\file")) {
                var encoded = new byte[8192];
                var buffer = new byte[4096];
                int nread, size;

                while ((nread = stream.Read (buffer, 0, buffer.Length)) > 0) {
                    size = encoder.EstimateOutputLength (nread);
                    if (encoded.Length < size)
                        Array.Resize (ref encoded, size);

                    // you'll need to step into this call
                    size = encoder.Encode (buffer, 0, buffer.Length, encoded);
                }

                // you might also have to step into this method
                size = encoder.Flush (buffer, 0, 0, encoded);
            }
        }
    }
}
```

**Comment by mikkeljohnsen** [comment] 2018-01-16 15:02
Encoding the PDF file that we are sending to Base64 is not producing the extra chars.

We are using this method.

`System.Convert.ToBase64String (File.ReadAllBytes(filepath));`

So it is in MimeKit that the extra chars are being created. What method is used in MimeKit ?

**Comment by jstedfast** [comment] 2018-01-16 15:10
The Base64Encoder that I referenced above.

**Comment by jstedfast** [comment] 2018-01-16 15:12
Can you send me the pdf so that I can test this?

**Comment by mikkeljohnsen** [comment] 2018-01-16 16:05
It do not matter what PDF or binary file you use. They all fail.

**Comment by jstedfast** [comment] 2018-01-16 16:12
So if you clone the MimeKit source code, build the MimeKit.Net45.sln solution, and run the Unit Tests... does the UnitTests.Encodings.EncoderTests.TestBase64Encode() test fail?

**Comment by jstedfast** [comment] 2018-01-16 17:33
I'm just going to close this as a runtime bug until someone can give me a way to reproduce it on any of the machines I have...

**Closed by jstedfast** 2018-01-16 17:33 UTC

**Comment by mikkeljohnsen** [comment] 2018-01-16 18:34
We don't have a Visual Studio on Windows 7. I will see if I have 5 hours to install VS (or what insane amount of time it takes to install VS on Windows)

It is the exact same binary code, Mono and app running on Windows 7 and 10.

We testet with your rutine for creating base64 and it gives no extra chars. So somewhere inside MimeKit it happens. It looks like a extra char is added for every ca. 7200 chars. Is there a buffer that concats the Base64 ?

The problem is, we now have to go back to using SmtpClient, because that works.

**Comment by jstedfast** [comment] 2018-01-16 21:03
The "buffer" is just the output stream. If there was a problem concatenating the encoded buffers, wouldn't it also show up on Windows 10, Linux and Mac (and not just Windows 7)?

**Comment by mikkeljohnsen** [comment] 2018-01-17 07:27
No, that is try. 

But you would not expect that the exact same binary code and exact same binary runtime (mono distributed along side the app), would add extra chars to the binary attachment base64 file on Windows 7 and not on Windows 10.

**Comment by mikkeljohnsen** [comment] 2018-01-17 09:40
Ok, So the error is not in MimeKit, if we print out the mime message just before we send it, everything is fine. We can grab the base64 encoding an decode it and the PDF looks fine.

But after it is send to the mail server, the file is corrupt. (extra chars is added).

**Comment by mikkeljohnsen** [comment] 2018-01-17 11:29
We have now tracked it down to with Wireshark and it is a "." that is added inside the base64 attached file, when send to the mail server.

So a combination of MailKit and Windows 7 adds "." in the base64 attachment.

It works fine when using SmtpClient.

**Comment by mikkeljohnsen** [comment] 2018-01-17 14:37
We have done the following and that solves the problem on Windows 7.

Not really sure why this solves it.

```diff --git a/MailKit/Net/Smtp/SmtpStream.cs b/MailKit/Net/Smtp/SmtpStream.cs
index eb27995c..4651f788 100644
--- a/MailKit/Net/Smtp/SmtpStream.cs
+++ b/MailKit/Net/Smtp/SmtpStream.cs
@@ -57,7 +57,7 @@ namespace MailKit.Net.Smtp {
               static readonly Encoding Latin1;
               static readonly Encoding UTF8;
               const int ReadAheadSize = 128;
-               const int BlockSize = 4096;
+               const int BlockSize = 520832;
               const int PadSize = 4;

               // I/O buffering

**Comment by jstedfast** [comment] 2018-01-17 15:46
I'll take a closer look at the smtp stream logic.

**Comment by mikkeljohnsen** [comment] 2018-01-17 15:49
That sounds great.

We are using version 1.22.0

**Comment by jstedfast** [comment] 2018-01-17 16:13
Can you get me a protocol log? I need to see *exactly* what is going on because I still can't reproduce the problem and I see nothing obvious in the code that could cause this.

**Comment by jstedfast** [comment] 2018-01-17 17:15
The following code snippet is a reduced text case that clones `SmtpDataFilter` and the relevant `SmtpStream`.

```csharp
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

using MimeKit;
using MimeKit.IO;
using MimeKit.IO.Filters;

namespace SmtpDataTest {
    class Program
    {
        public static void Main (string[] args)
        {
            var options = FormatOptions.Default.Clone ();
            options.NewLineFormat = NewLineFormat.Dos;

            var message = new MimeMessage ();
            message.From.Add (new MailboxAddress ("My Name", "myname@mydomain.com"));
            message.To.Add (new MailboxAddress ("My Name", "myname@mydomain.com"));
            message.Subject = "This is a test message for issue #633";

            var builder = new BodyBuilder ();
            builder.TextBody = "This is a test message attempting to reproduce the corruption described in issue #633.\r\n";

            for (int i = 0; i < args.Length; i++)
                builder.Attachments.Add (args[0]);

            message.Body = builder.ToMessageBody ();

            using (var stream = File.Create ("message.txt")) {
                using (var smtp = new SmtpStream (stream)) {
                    using (var filtered = new FilteredStream (smtp)) {
                        filtered.Add (new SmtpDataFilter ());

                        message.WriteTo (options, filtered);
                        filtered.Flush ();
                    }
                }
            }
        }
    }

    class SmtpDataFilter : MimeFilterBase
	{
		bool bol = true;

		/// <summary>
		/// Filter the specified input.
		/// </summary>
		/// <returns>The filtered output.</returns>
		/// <param name="input">The input buffer.</param>
		/// <param name="startIndex">The starting index of the input buffer.</param>
		/// <param name="length">Length.</param>
		/// <param name="outputIndex">Output index.</param>
		/// <param name="outputLength">Output length.</param>
		/// <param name="flush">If set to <c>true</c> flush.</param>
		protected override byte[] Filter (byte[] input, int startIndex, int length, out int outputIndex, out int outputLength, bool flush)
		{
			int inputEnd = startIndex + length;
			bool escape = bol;
			int ndots = 0;

			for (int i = startIndex; i < inputEnd; i++) {
				byte c = input[i];

				if (c == (byte) '.' && escape) {
					escape = false;
					ndots++;
				} else {
					escape = c == (byte) '\n';
				}
			}

			EnsureOutputSize (length + ndots, false);
			int index = 0;

			for (int i = startIndex; i < inputEnd; i++) {
				byte c = input[i];

				if (c == (byte) '.' && bol) {
					OutputBuffer[index++] = (byte) '.';
					bol = false;
				} else {
					bol = c == (byte) '\n';
				}

				OutputBuffer[index++] = c;
			}

			outputLength = index;
			outputIndex = 0;

			return OutputBuffer;
		}

		/// <summary>
		/// Resets the filter.
		/// </summary>
		public override void Reset ()
		{
			base.Reset ();
			bol = true;
		}
	}

    class SmtpStream : Stream, ICancellableStream
	{
		const int ReadAheadSize = 128;
		const int BlockSize = 4096;
		const int PadSize = 4;

		readonly byte[] output = new byte[BlockSize];
		int outputIndex;
		bool disposed;

		/// <summary>
		/// Initializes a new instance of the <see cref="MailKit.Net.Smtp.SmtpStream"/> class.
		/// </summary>
		/// <remarks>
		/// Creates a new <see cref="SmtpStream"/>.
		/// </remarks>
		/// <param name="source">The underlying network stream.</param>
		/// <param name="socket">The underlying network socket.</param>
		/// <param name="protocolLogger">The protocol logger.</param>
		public SmtpStream (Stream source)
		{
			Stream = source;
		}

		/// <summary>
		/// Get or sets the underlying network stream.
		/// </summary>
		/// <remarks>
		/// Gets or sets the underlying network stream.
		/// </remarks>
		/// <value>The underlying network stream.</value>
		public Stream Stream {
			get; internal set;
		}

		/// <summary>
		/// Get whether the stream supports reading.
		/// </summary>
		/// <remarks>
		/// Gets whether the stream supports reading.
		/// </remarks>
		/// <value><c>true</c> if the stream supports reading; otherwise, <c>false</c>.</value>
		public override bool CanRead {
			get { return Stream.CanRead; }
		}

		/// <summary>
		/// Get whether the stream supports writing.
		/// </summary>
		/// <remarks>
		/// Gets whether the stream supports writing.
		/// </remarks>
		/// <value><c>true</c> if the stream supports writing; otherwise, <c>false</c>.</value>
		public override bool CanWrite {
			get { return Stream.CanWrite; }
		}

		/// <summary>
		/// Get whether the stream supports seeking.
		/// </summary>
		/// <remarks>
		/// Gets whether the stream supports seeking.
		/// </remarks>
		/// <value><c>true</c> if the stream supports seeking; otherwise, <c>false</c>.</value>
		public override bool CanSeek {
			get { return false; }
		}

		/// <summary>
		/// Get whether the stream supports I/O timeouts.
		/// </summary>
		/// <remarks>
		/// Gets whether the stream supports I/O timeouts.
		/// </remarks>
		/// <value><c>true</c> if the stream supports I/O timeouts; otherwise, <c>false</c>.</value>
		public override bool CanTimeout {
			get { return Stream.CanTimeout; }
		}

		/// <summary>
		/// Get or set a value, in milliseconds, that determines how long the stream will attempt to read before timing out.
		/// </summary>
		/// <remarks>
		/// Gets or sets a value, in milliseconds, that determines how long the stream will attempt to read before timing out.
		/// </remarks>
		/// <returns>A value, in milliseconds, that determines how long the stream will attempt to read before timing out.</returns>
		/// <value>The read timeout.</value>
		public override int ReadTimeout {
			get { return Stream.ReadTimeout; }
			set { Stream.ReadTimeout = value; }
		}

		/// <summary>
		/// Get or set a value, in milliseconds, that determines how long the stream will attempt to write before timing out.
		/// </summary>
		/// <remarks>
		/// Gets or sets a value, in milliseconds, that determines how long the stream will attempt to write before timing out.
		/// </remarks>
		/// <returns>A value, in milliseconds, that determines how long the stream will attempt to write before timing out.</returns>
		/// <value>The write timeout.</value>
		public override int WriteTimeout {
			get { return Stream.WriteTimeout; }
			set { Stream.WriteTimeout = value; }
		}

		/// <summary>
		/// Get or set the position within the current stream.
		/// </summary>
		/// <remarks>
		/// Gets or sets the position within the current stream.
		/// </remarks>
		/// <returns>The current position within the stream.</returns>
		/// <value>The position of the stream.</value>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support seeking.
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		public override long Position {
			get { return Stream.Position; }
			set { Stream.Position = value; }
		}

		/// <summary>
		/// Get the length of the stream, in bytes.
		/// </summary>
		/// <remarks>
		/// Gets the length of the stream, in bytes.
		/// </remarks>
		/// <returns>A long value representing the length of the stream in bytes.</returns>
		/// <value>The length of the stream.</value>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support seeking.
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		public override long Length {
			get { return Stream.Length; }
		}

		static void ValidateArguments (byte[] buffer, int offset, int count)
		{
			if (buffer == null)
				throw new ArgumentNullException (nameof (buffer));

			if (offset < 0 || offset > buffer.Length)
				throw new ArgumentOutOfRangeException (nameof (offset));

			if (count < 0 || count > (buffer.Length - offset))
				throw new ArgumentOutOfRangeException (nameof (count));
		}

		void CheckDisposed ()
		{
			if (disposed)
				throw new ObjectDisposedException (nameof (SmtpStream));
		}

		/// <summary>
		/// Reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </summary>
		/// <remarks>
		/// Reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </remarks>
		/// <returns>The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many
		/// bytes are not currently available, or zero (0) if the end of the stream has been reached.</returns>
		/// <param name="buffer">The buffer.</param>
		/// <param name="offset">The buffer offset.</param>
		/// <param name="count">The number of bytes to read.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public int Read (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			throw new NotImplementedException ();
		}

		/// <summary>
		/// Reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </summary>
		/// <remarks>
		/// Reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </remarks>
		/// <returns>The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many
		/// bytes are not currently available, or zero (0) if the end of the stream has been reached.</returns>
		/// <param name="buffer">The buffer.</param>
		/// <param name="offset">The buffer offset.</param>
		/// <param name="count">The number of bytes to read.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override int Read (byte[] buffer, int offset, int count)
		{
			return Read (buffer, offset, count, CancellationToken.None);
		}

		/// <summary>
		/// Asynchronously reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </summary>
		/// <remarks>
		/// Reads a sequence of bytes from the stream and advances the position
		/// within the stream by the number of bytes read.
		/// </remarks>
		/// <returns>The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many
		/// bytes are not currently available, or zero (0) if the end of the stream has been reached.</returns>
		/// <param name="buffer">The buffer.</param>
		/// <param name="offset">The buffer offset.</param>
		/// <param name="count">The number of bytes to read.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override Task<int> ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			throw new NotImplementedException ();
		}

		async Task WriteAsync (byte[] buffer, int offset, int count, bool doAsync, CancellationToken cancellationToken)
		{
			CheckDisposed ();

			ValidateArguments (buffer, offset, count);

			try {
				int index = offset;
				int left = count;

				while (left > 0) {
					int n = Math.Min (BlockSize - outputIndex, left);

					if (outputIndex > 0 || n < BlockSize) {
						// append the data to the output buffer
						Buffer.BlockCopy (buffer, index, output, outputIndex, n);
						outputIndex += n;
						index += n;
						left -= n;
					}

					if (outputIndex == BlockSize) {
						// flush the output buffer
						if (doAsync) {
							await Stream.WriteAsync (output, 0, BlockSize, cancellationToken).ConfigureAwait (false);
						} else {
							//Poll (SelectMode.SelectWrite, cancellationToken);
							Stream.Write (output, 0, BlockSize);
						}
						//logger.LogClient (output, 0, BlockSize);
						outputIndex = 0;
					}

					if (outputIndex == 0) {
						// write blocks of data to the stream without buffering
						while (left >= BlockSize) {
							if (doAsync) {
								await Stream.WriteAsync (buffer, index, BlockSize, cancellationToken).ConfigureAwait (false);
							} else {
								//Poll (SelectMode.SelectWrite, cancellationToken);
								Stream.Write (buffer, index, BlockSize);
							}
							//logger.LogClient (buffer, index, BlockSize);
							index += BlockSize;
							left -= BlockSize;
						}
					}
				}
			} catch {
				//IsConnected = false;
				throw;
			}
		}

		/// <summary>
		/// Writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </summary>
		/// <remarks>
		/// Writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </remarks>
		/// <param name='buffer'>The buffer to write.</param>
		/// <param name='offset'>The offset of the first byte to write.</param>
		/// <param name='count'>The number of bytes to write.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public void Write (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			WriteAsync (buffer, offset, count, false, cancellationToken).GetAwaiter ().GetResult ();
		}

		/// <summary>
		/// Writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </summary>
		/// <remarks>
		/// Writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </remarks>
		/// <param name='buffer'>The buffer to write.</param>
		/// <param name='offset'>The offset of the first byte to write.</param>
		/// <param name='count'>The number of bytes to write.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override void Write (byte[] buffer, int offset, int count)
		{
			Write (buffer, offset, count, CancellationToken.None);
		}

		/// <summary>
		/// Asynchronously writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </summary>
		/// <remarks>
		/// Writes a sequence of bytes to the stream and advances the current
		/// position within this stream by the number of bytes written.
		/// </remarks>
		/// <returns>A task that represents the asynchronous write operation.</returns>
		/// <param name='buffer'>The buffer to write.</param>
		/// <param name='offset'>The offset of the first byte to write.</param>
		/// <param name='count'>The number of bytes to write.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <paramref name="buffer"/> is <c>null</c>.
		/// </exception>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <para><paramref name="offset"/> is less than zero or greater than the length of <paramref name="buffer"/>.</para>
		/// <para>-or-</para>
		/// <para>The <paramref name="buffer"/> is not large enough to contain <paramref name="count"/> bytes strting
		/// at the specified <paramref name="offset"/>.</para>
		/// </exception>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override Task WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			return WriteAsync (buffer, offset, count, true, cancellationToken);
		}

		async Task FlushAsync (bool doAsync, CancellationToken cancellationToken)
		{
			CheckDisposed ();

			if (outputIndex == 0)
				return;

			try {
				if (doAsync) {
					await Stream.WriteAsync (output, 0, outputIndex, cancellationToken).ConfigureAwait (false);
					await Stream.FlushAsync (cancellationToken).ConfigureAwait (false);
				} else {
					//Poll (SelectMode.SelectWrite, cancellationToken);
					Stream.Write (output, 0, outputIndex);
					Stream.Flush ();
				}
				//logger.LogClient (output, 0, outputIndex);
				outputIndex = 0;
			} catch {
				//IsConnected = false;
				throw;
			}
		}

		/// <summary>
		/// Clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </summary>
		/// <remarks>
		/// Clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </remarks>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public void Flush (CancellationToken cancellationToken)
		{
			FlushAsync (false, cancellationToken).GetAwaiter ().GetResult ();
		}

		/// <summary>
		/// Clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </summary>
		/// <remarks>
		/// Clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </remarks>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override void Flush ()
		{
			Flush (CancellationToken.None);
		}

		/// <summary>
		/// Asynchronously clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </summary>
		/// <remarks>
		/// Clears all buffers for this stream and causes any buffered data to be written
		/// to the underlying device.
		/// </remarks>
		/// <returns>A task that represents the asynchronous flush operation.</returns>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <exception cref="System.ObjectDisposedException">
		/// The stream has been disposed.
		/// </exception>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support writing.
		/// </exception>
		/// <exception cref="System.OperationCanceledException">
		/// The operation was canceled via the cancellation token.
		/// </exception>
		/// <exception cref="System.IO.IOException">
		/// An I/O error occurred.
		/// </exception>
		public override Task FlushAsync (CancellationToken cancellationToken)
		{
			return FlushAsync (true, cancellationToken);
		}

		/// <summary>
		/// Sets the position within the current stream.
		/// </summary>
		/// <returns>The new position within the stream.</returns>
		/// <param name="offset">The offset into the stream relative to the <paramref name="origin"/>.</param>
		/// <param name="origin">The origin to seek from.</param>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support seeking.
		/// </exception>
		public override long Seek (long offset, SeekOrigin origin)
		{
			throw new NotSupportedException ();
		}

		/// <summary>
		/// Sets the length of the stream.
		/// </summary>
		/// <param name="value">The desired length of the stream in bytes.</param>
		/// <exception cref="System.NotSupportedException">
		/// The stream does not support setting the length.
		/// </exception>
		public override void SetLength (long value)
		{
			throw new NotSupportedException ();
		}

		/// <summary>
		/// Releases the unmanaged resources used by the <see cref="SmtpStream"/> and
		/// optionally releases the managed resources.
		/// </summary>
		/// <remarks>
		/// Releases the unmanaged resources used by the <see cref="SmtpStream"/> and
		/// optionally releases the managed resources.
		/// </remarks>
		/// <param name="disposing"><c>true</c> to release both managed and unmanaged resources;
		/// <c>false</c> to release only the unmanaged resources.</param>
		protected override void Dispose (bool disposing)
		{
			if (disposing && !disposed) {
				//IsConnected = false;
				Stream.Dispose ();
			}

			disposed = true;

			base.Dispose (disposing);
		}
	}
}
```

**Comment by jstedfast** [comment] 2018-01-17 17:15
Can you reproduce the problem with this test case?

**Comment by madsjohnsen** [comment] 2018-01-19 11:30
Apologies for the delay.
No, the test case does not reproduce the problem. During testing I also did more or less the same thing of writing to file instead of the network stream, and did not see the problem there either.

I have used the following PDF for the test case, and for an example containing the invalid (nul) symbols.
[https://tools.ietf.org/pdf/rfc4648.pdf](url)

[message_minimal.txt](https://github.com/jstedfast/MailKit/files/1646331/message_minimal.txt)
[wireshark-tcpstream.txt](https://github.com/jstedfast/MailKit/files/1646332/wireshark-tcpstream.txt)
 (replaced some information with \_*\_)

**Comment by jstedfast** [comment] 2018-01-19 14:02
Hmmm, my test program should have reproduced the problem if the problem is in MailKit because that's the entire stack of code that the message passes through when writing it to the TCP network stream (the SMTP data filter *and* the SmtpStream that buffers the output to the underlying NetworkStream).

The only difference, obviously, is the code is using a FileStream instead of a network socket, but any bug in that level of code is, again, not in MailKit.

If it is a NetworkStream or a Socket bug, then there's nothing I can do in MailKit to work around it.

There's no way I can debug this further :(

Did you try getting a Protocol Log using MailKit's [ProtocolLog](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) API? Does the resulting log show this same corruption? If so, maybe I am missing something in my test program.
