### ISSUE TITLE
ImapUtils.ReadNStringTokenAsync seem fail on parse some special ENVELOPE case

### ISSUE THREAD

**Issue by Deliay** [jstedfast/MailKit#932] opened 2019-10-14 07:58 UTC
**Describe the bug**
ImapUtils.ReadNStringTokenAsync seem fail on parse some special ENVELOPE case

**Platform (please complete the following information):**
 - OS: Windows, Linux
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core 2.2
 - MimeKit Version: 2.3.2

**Screenshots**
MailKit: 
```
C: B00000008 UID FETCH 9174 (UID ENVELOPE)
S: * 450 FETCH (UID 9174 ENVELOPE ("Tue, 24 Sep 2019 09:48:05 +0800" "=?GBK?B?sbG+qdW9x/jI1bGose0=?=" (("=?GBK?B?yv2+3bfWzvbQodfp?=" NIL "unkonwn-name" "unknown-domain")) (("=?GBK?B?yv2+3bfWzvbQodfp?=" NIL "unkonwn-name" "unknown-domain")) (("=?GBK?B?yv2+3bfWzvbQodfp?=" NIL "unkonwn-name" "unknown-domain")) NIL NIL NIL))
S: B00000008 OK UID FETCH Completed
```

MailKit:
![Screenshot_20191014_154901](https://user-images.githubusercontent.com/5661435/66735895-3c90af00-ee9a-11e9-8445-fd4f29963942.png)

**Additional context**
StackTrace:
```
  at MailKit.Net.Imap.ImapUtils.ReadNStringTokenAsync(ImapEngine engine, String format, Boolean rfc2047, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseEnvelopeAsync(ImapEngine engine, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItemsAsync(ImapEngine engine, MessageSummary message, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItemsAsync(ImapEngine engine, ImapCommand ic, Int32 index, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 uids, MessageSummaryItems items, Boolean doAsync, CancellationToken cancellationToken)
   at _.Common.GlobalImapFolderHelper.CapabilityFetchAsync(IMailFolder folder, IList`1 uids, MessageSummaryItems items, CancellationToken cancellationToken)
```

**Comment by jstedfast** [comment] 2019-10-14 13:44
The problem is that your IMAP server is sending a broken ENVELOPE value that does not include the In-Reply-To header value.

The syntax of the ENVELOPE response value is as follows:

```
envelope        = "(" env-date SP env-subject SP env-from SP
                  env-sender SP env-reply-to SP env-to SP env-cc SP
                  env-bcc SP env-in-reply-to SP env-message-id ")"
```

As you can see from the value you pasted into the bug report (thanks for narrowing it down, btw, that was super helpful!), that value is missing both the `env-in-reply-to` *and* the `env-message-id` tokens.

I already had a work-around for a missing `env-message-id` token (issue #669), so I added a similar work-around for this issue as well.

I usually don't make releases more than about once a month and unfortunately I *just* made a release yesterday, so it'll probably be a while before I make the next one.

That said, I *do* have an automated build & packaging system setup to publish a build for each commit I do located at https://www.myget.org/feed/mimekit/package/nuget/MailKit

If you install MailKit v2.3.2.5 (or later), it will contain the fix I committed above. FWIW, v2.3.2.4 is identical to the nuget published on nuget.org, so the only difference between the official 2.3.2 release and 2.3.2.5 is the fix for your bug.

Thanks for the bug report and taking the time to narrow down the exact response that MailKit was failing on! That kind of exceptional bug reporting really helps save me time and I am very thankful!

**Closed by jstedfast** 2019-10-14 13:44 UTC

**Comment by jstedfast** [comment] 2019-11-03 01:37
MailKit 2.4.0 has just been released with this fix.
