### ISSUE TITLE
MailFolder.SetFlags(list<int>) - wrong indexing when out of order

### ISSUE THREAD

**Issue by Josef-Haupt** [jstedfast/MailKit#1150] opened 2021-02-12 08:33 UTC
**Describe the bug**
The `MailFolder.SetFlags(IList<Int32>, MessageFlags, Boolean, CancellationToken)` method does not work as I expected it to.
When given two indices where the second one is decremented by 1 the imap command should look like this:
`"STORE 3,2 FLAGS.SILENT (\Seen)"`
But it will actually be:
`STORE 3:2 FLAGS.SILENT (\Seen)`
The imap server will then not mark any message as seen.

Is this the expected behaviour? I could not find any mention of it in the [docs](http://www.mimekit.net/docs/html/M_MailKit_MailFolder_SetFlags_6.htm).

When the indices are ordered, the command will work as expected.

Thank you for your time.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 5
 - MailKit Version: 2.10.1

**To Reproduce**
1. Suppose I have 3 unread messages in my inbox.
2. And I want to mark the last and second to last as seen:
```csharp
using var imap = new ImapClient();
await imap.ConnectAsync("127.0.0.1", 143, false);
await imap.AuthenticateAsync("imap@mail.local", "1234");
var folder = imap.Inbox;
await folder.OpenAsync(FolderAccess.ReadWrite);
folder.SetFlags(new int[] { 2, 1 }, MessageFlags.Seen, true);
```

**Expected behavior**
TCP - 127.0.0.1 connected to 127.0.0.1:143.
SENT: * OK IMAPrev1
RECEIVED: A00000000 CAPABILITY
SENT: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk[nl]A00000000 OK CAPABILITY completed
RECEIVED: A00000001 LOGIN imap@mail.local ***
SENT: A00000001 OK LOGIN completed
RECEIVED: A00000002 CAPABILITY
SENT: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk[nl]A00000002 OK CAPABILITY completed
RECEIVED: A00000003 NAMESPACE
SENT: * NAMESPACE (("" ".")) NIL (("#Public" "."))[nl]A00000003 OK namespace command complete
RECEIVED: A00000004 LIST "" "INBOX"
SENT: * LIST (\HasNoChildren) "." "INBOX"[nl]A00000004 OK LIST completed
RECEIVED: A00000005 SELECT INBOX
SENT: * 3 EXISTS[nl]* 0 RECENT[nl]* FLAGS (\Deleted \Seen \Draft \Answered \Flagged)[nl]* OK [UIDVALIDITY 1610117322] current uidvalidity[nl]* OK [UNSEEN 4905] unseen messages[nl]* OK [UIDNEXT 4910] next uid[nl]* OK [PERMANENTFLAGS (\Deleted \Seen \Draft \Answered \Flagged)] limited[nl]A00000005 OK [READ-WRITE] SELECT completed
**RECEIVED: A00000006 STORE 3, 2 FLAGS.SILENT (\Seen)**
SENT: A00000006 OK STORE completed

**Screenshots**
The actual command:
![image](https://user-images.githubusercontent.com/35149496/107745392-88649a00-6d14-11eb-86f8-f5c028eaf4db.png)

**Comment by jstedfast** [comment] 2021-02-12 15:36
Sounds like a bug in the IMAP server, because ranges aren't required to be ascending (they can also be descending).

From [rfc3501](https://tools.ietf.org/html/rfc3501):

```
seq-range       = seq-number ":" seq-number
                    ; two seq-number values and all values between
                    ; these two regardless of order.
                    ; Example: 2:4 and 4:2 are equivalent and indicate
                    ; values 2, 3, and 4.
                    ; Example: a unique identifier sequence range of
                    ; 3291:* includes the UID of the last message in
                    ; the mailbox, even if that value is less than 3291.
```

**Comment by Josef-Haupt** [comment] 2021-02-12 15:46
Your are right, Mailkit works correctly. 
It seems like its a probem with hmailserver.

Thanks for the insight!

**Comment by jstedfast** [comment] 2021-02-12 15:54
We don't have to close this yet. While I agree it's not a bug in MailKit, I might be able to detect that it's hMailServer and add in a work-around for this server bug.

**Comment by jstedfast** [comment] 2021-02-12 16:11
This should be fixed now for all commands that take sequence ranges

**Comment by jstedfast** [comment] 2021-02-12 16:28
FWIW, even though this is fixed now, I would highly recommend:

1. switching over to using UIDs instead of indexes if at all possible
2. sorting indexes/uids because it allows mailkit to send more efficient command-lines to the server

example:

1, 2, 3, 4, 5, .. 9999 => 1:9999

if they are in random order, that string can become very long

**Closed by jstedfast** 2021-02-12 16:28 UTC
Labels: compatibility, server-bug
